# Generated by Django 5.1.15 on 2026-03-02 05:08

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('base_legal', models.CharField(blank=True, help_text='Referencia legal (ej: Ley 29409, DL 713 Art. 17)', max_length=200)),
                ('dias_max', models.PositiveSmallIntegerField(default=0, help_text='0 = sin límite', verbose_name='Días Máximos')),
                ('pagado', models.BooleanField(default=True, help_text='Si el permiso es con goce de remuneración', verbose_name='¿Pagado?')),
                ('requiere_sustento', models.BooleanField(default=False, help_text='Si requiere documento de sustento (certificado médico, etc.)')),
                ('descuenta_vacaciones', models.BooleanField(default=False, help_text='Si se descuenta del saldo vacacional')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Tipo de Permiso',
                'verbose_name_plural': 'Tipos de Permiso',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SaldoVacacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(help_text='Fecha de inicio del año de servicio', verbose_name='Inicio Período')),
                ('periodo_fin', models.DateField(help_text='Fecha de fin del año de servicio', verbose_name='Fin Período')),
                ('dias_derecho', models.PositiveSmallIntegerField(default=30, help_text='30 días calendario por ley (DL 713)', verbose_name='Días de Derecho')),
                ('dias_gozados', models.PositiveSmallIntegerField(default=0, verbose_name='Días Gozados')),
                ('dias_vendidos', models.PositiveSmallIntegerField(default=0, help_text='Máximo 15 días (DL 713 Art. 19)', verbose_name='Días Vendidos')),
                ('dias_pendientes', models.PositiveSmallIntegerField(default=30, verbose_name='Días Pendientes')),
                ('dias_truncos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Días proporcionales al cese (para liquidación)', max_digits=5, verbose_name='Días Truncos')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcialmente Gozado'), ('GOZADO', 'Completamente Gozado'), ('TRUNCO', 'Trunco (Cesado)')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_vacacionales', to='personal.personal', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Saldo Vacacional',
                'verbose_name_plural': 'Saldos Vacacionales',
                'ordering': ['-periodo_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudVacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('dias_calendario', models.PositiveSmallIntegerField(help_text='Días calendario solicitados', verbose_name='Días Calendario')),
                ('dias_habiles', models.PositiveSmallIntegerField(default=0, verbose_name='Días Hábiles')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo/Observaciones')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente Aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EN_GOCE', 'En Goce'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vacacion', to='personal.personal', verbose_name='Trabajador')),
                ('saldo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='vacaciones.saldovacacional', verbose_name='Período Vacacional')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Vacaciones',
                'verbose_name_plural': 'Solicitudes de Vacaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('dias', models.PositiveSmallIntegerField(verbose_name='Días Solicitados')),
                ('horas', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Para permisos por horas', max_digits=4, verbose_name='Horas (si aplica)')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('sustento', models.FileField(blank=True, help_text='Certificado médico, partida, etc.', null=True, upload_to='permisos/sustentos/%Y/%m/', verbose_name='Documento Sustento')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente Aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_permiso', to='personal.personal', verbose_name='Trabajador')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_registrados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='vacaciones.tipopermiso', verbose_name='Tipo de Permiso')),
            ],
            options={
                'verbose_name': 'Solicitud de Permiso',
                'verbose_name_plural': 'Solicitudes de Permisos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='VentaVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_vendidos', models.PositiveSmallIntegerField(help_text='Máximo 15 días por período (DL 713 Art. 19)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)], verbose_name='Días Vendidos')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (S/)')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_vacaciones', to='personal.personal')),
                ('saldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='vacaciones.saldovacacional')),
            ],
            options={
                'verbose_name': 'Venta de Vacaciones',
                'verbose_name_plural': 'Ventas de Vacaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='saldovacacional',
            index=models.Index(fields=['personal', 'estado'], name='vacaciones__persona_415629_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saldovacacional',
            unique_together={('personal', 'periodo_inicio')},
        ),
        migrations.AddIndex(
            model_name='solicitudvacacion',
            index=models.Index(fields=['personal', 'estado'], name='vacaciones__persona_156953_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacacion',
            index=models.Index(fields=['-fecha_inicio'], name='vacaciones__fecha_i_a16bec_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpermiso',
            index=models.Index(fields=['personal', 'estado'], name='vacaciones__persona_8b3e60_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpermiso',
            index=models.Index(fields=['tipo', 'estado'], name='vacaciones__tipo_id_b1cffc_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpermiso',
            index=models.Index(fields=['-fecha_inicio'], name='vacaciones__fecha_i_1e608f_idx'),
        ),
    ]
