# Generated by Django 5.1.15 on 2026-03-02 02:12

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('max_cuotas', models.PositiveSmallIntegerField(default=12, verbose_name='Máximo de Cuotas')),
                ('tasa_interes_mensual', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='0 = sin interés', max_digits=5, verbose_name='Tasa Interés Mensual (%)')),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío = sin límite', max_digits=10, null=True, verbose_name='Monto Máximo')),
                ('requiere_aprobacion', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Préstamo',
                'verbose_name_plural': 'Tipos de Préstamo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Monto Solicitado')),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Aprobado')),
                ('num_cuotas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='N° Cuotas')),
                ('cuota_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cuota Mensual')),
                ('tasa_interes', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=5, verbose_name='Tasa Interés (%)')),
                ('fecha_solicitud', models.DateField(default=datetime.date.today, verbose_name='Fecha Solicitud')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_primer_descuento', models.DateField(blank=True, help_text='Período desde el cual se descuenta', null=True, verbose_name='Inicio Descuento')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente Aprobación'), ('APROBADO', 'Aprobado'), ('EN_CURSO', 'En Curso'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=12)),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='personal.personal', verbose_name='Trabajador')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_registrados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='prestamos.tipoprestamo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='CuotaPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='N°')),
                ('periodo', models.DateField(verbose_name='Período')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PARCIAL', 'Pago Parcial'), ('CONDONADO', 'Condonado')], default='PENDIENTE', max_length=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('referencia_nomina', models.CharField(blank=True, max_length=100)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='prestamos.prestamo')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['prestamo', 'numero'],
                'unique_together': {('prestamo', 'numero')},
            },
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['personal', 'estado'], name='prestamos_p_persona_148a74_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['-fecha_solicitud'], name='prestamos_p_fecha_s_b3fdaa_idx'),
        ),
    ]
