# Generated by Django 5.1.15 on 2026-03-02 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar_colapsado', models.BooleanField(default=False, verbose_name='Sidebar colapsado por defecto')),
                ('items_por_pagina', models.PositiveSmallIntegerField(choices=[(10, '10 por página'), (20, '20 por página'), (30, '30 por página'), (50, '50 por página')], default=20, verbose_name='Elementos por página')),
                ('tema', models.CharField(choices=[('AUTO', 'Sistema (auto)'), ('LIGHT', 'Claro'), ('DARK', 'Oscuro')], default='AUTO', max_length=6, verbose_name='Tema de color')),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5, verbose_name='Idioma')),
                ('notif_email_habilitado', models.BooleanField(default=True, verbose_name='Recibir notificaciones por email')),
                ('notif_contratos', models.BooleanField(default=True, verbose_name='Alertas de contratos y período de prueba')),
                ('notif_vacaciones', models.BooleanField(default=True, verbose_name='Alertas de vacaciones')),
                ('notif_documentos', models.BooleanField(default=True, verbose_name='Alertas de documentos laborales')),
                ('dashboard_widgets', models.JSONField(blank=True, default=list, help_text='Lista de slugs de widgets que el usuario quiere ver en su home.', verbose_name='Widgets del dashboard activos')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de Usuario',
                'verbose_name_plural': 'Preferencias de Usuarios',
            },
        ),
    ]
