# Generated by Django 5.1.15 on 2026-03-02 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_preferencia_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('personal', 'Personal'), ('asistencia', 'Asistencia & Tareo'), ('nominas', 'Nóminas'), ('vacaciones', 'Vacaciones & Permisos'), ('documentos', 'Documentos'), ('capacitaciones', 'Capacitaciones'), ('disciplinaria', 'Disciplinaria'), ('evaluaciones', 'Evaluaciones'), ('encuestas', 'Encuestas'), ('salarios', 'Salarios'), ('reclutamiento', 'Reclutamiento'), ('comunicaciones', 'Comunicaciones'), ('prestamos', 'Préstamos'), ('viaticos', 'Viáticos'), ('onboarding', 'Onboarding'), ('calendario', 'Calendario'), ('analytics', 'Analytics'), ('configuracion', 'Configuración')], max_length=30, verbose_name='Módulo')),
                ('puede_ver', models.BooleanField(default=False, verbose_name='Ver')),
                ('puede_crear', models.BooleanField(default=False, verbose_name='Crear')),
                ('puede_editar', models.BooleanField(default=False, verbose_name='Editar')),
                ('puede_aprobar', models.BooleanField(default=False, verbose_name='Aprobar')),
                ('puede_exportar', models.BooleanField(default=False, verbose_name='Exportar')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_modulos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de Módulo',
                'verbose_name_plural': 'Permisos de Módulos',
                'ordering': ['usuario', 'modulo'],
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
