# Generated by Django 5.1.15 on 2026-03-02 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('tipo', models.CharField(choices=[('VACACION', 'Vacaciones'), ('PERMISO', 'Permiso'), ('FERIADO', 'Feriado'), ('CUMPLEANOS', 'Cumpleanos'), ('TURNO', 'Turno'), ('REUNION', 'Reunion'), ('OTRO', 'Otro')], default='OTRO', max_length=12, verbose_name='Tipo de Evento')),
                ('todo_el_dia', models.BooleanField(default=True, verbose_name='Todo el dia')),
                ('color', models.CharField(blank=True, help_text='Hex color (#RRGGBB). Si vacio, se usa el color por tipo.', max_length=7, verbose_name='Color')),
                ('recurrente', models.BooleanField(default=False, verbose_name='Recurrente')),
                ('privado', models.BooleanField(default=False, help_text='Si es privado, solo el creador y el personal asignado lo ven.', verbose_name='Privado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_calendario', to='personal.area', verbose_name='Area')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to='personal.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Evento de Calendario',
                'verbose_name_plural': 'Eventos de Calendario',
                'ordering': ['fecha_inicio'],
                'indexes': [models.Index(fields=['fecha_inicio', 'fecha_fin'], name='calendario__fecha_i_7e3f1a_idx'), models.Index(fields=['tipo'], name='calendario__tipo_4ef951_idx'), models.Index(fields=['personal'], name='calendario__persona_482770_idx'), models.Index(fields=['area'], name='calendario__area_id_b058d2_idx')],
            },
        ),
    ]
