# Generated by Django 5.1.15 on 2026-03-02 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaRRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('ROTACION', 'Rotación'), ('ASISTENCIA', 'Asistencia'), ('DOCUMENTOS', 'Documentos vencidos'), ('VACACIONES', 'Vacaciones pendientes'), ('CAPACITACION', 'Capacitación'), ('DISCIPLINARIA', 'Disciplinaria'), ('OTRO', 'Otro')], max_length=20)),
                ('severidad', models.CharField(choices=[('INFO', 'Informativa'), ('WARN', 'Advertencia'), ('CRITICAL', 'Crítica')], default='INFO', max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RESUELTA', 'Resuelta'), ('DESCARTADA', 'Descartada')], default='ACTIVA', max_length=15)),
                ('valor_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor actual')),
                ('valor_umbral', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Umbral de alerta')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('notas_resolucion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.area', verbose_name='Área afectada')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta RRHH',
                'verbose_name_plural': 'Alertas RRHH',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes del snapshot', verbose_name='Periodo')),
                ('total_empleados', models.PositiveIntegerField(default=0)),
                ('empleados_staff', models.PositiveIntegerField(default=0)),
                ('empleados_rco', models.PositiveIntegerField(default=0)),
                ('altas_mes', models.PositiveIntegerField(default=0, verbose_name='Ingresos del mes')),
                ('bajas_mes', models.PositiveIntegerField(default=0, verbose_name='Ceses del mes')),
                ('tasa_rotacion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa de Rotación %')),
                ('tasa_rotacion_voluntaria', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rotación Voluntaria %')),
                ('tasa_asistencia', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tasa de Asistencia %')),
                ('total_he_mes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total HE del mes')),
                ('promedio_he_persona', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Promedio HE/persona')),
                ('dias_vacaciones_pendientes', models.PositiveIntegerField(default=0, verbose_name='Días vacaciones pendientes (total)')),
                ('promedio_dias_pendientes', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Promedio días pendientes/persona')),
                ('horas_capacitacion_mes', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Horas capacitación del mes')),
                ('empleados_capacitados', models.PositiveIntegerField(default=0, verbose_name='Empleados capacitados')),
                ('cobertura_capacitacion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cobertura capacitación %')),
                ('costo_nomina_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Costo nómina bruto S/')),
                ('costo_promedio_empleado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo promedio/empleado S/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot KPI',
                'verbose_name_plural': 'Snapshots KPIs',
                'ordering': ['-periodo'],
                'unique_together': {('periodo',)},
            },
        ),
    ]
