# Generated by Django 5.1.15 on 2026-03-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertarrhh',
            name='categoria',
            field=models.CharField(choices=[('ROTACION', 'Rotación'), ('ASISTENCIA', 'Asistencia'), ('DOCUMENTOS', 'Documentos vencidos'), ('VACACIONES', 'Vacaciones pendientes'), ('CAPACITACION', 'Capacitación'), ('DISCIPLINARIA', 'Disciplinaria'), ('CONTRATOS', 'Contratos y período de prueba'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
