# Generated by Django 5.1.15 on 2026-03-02 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0011_personal_grupo_tareo_condicion_codigos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(default='fa-folder', help_text='Clase FontAwesome (ej: fa-folder, fa-hard-hat, fa-file-contract)', max_length=50)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Documento',
                'verbose_name_plural': 'Categorías de Documento',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('obligatorio', models.BooleanField(default=False, help_text='Si es obligatorio, aparecerá como "faltante" cuando no exista.')),
                ('vence', models.BooleanField(default=False, help_text='Indica si este tipo de documento tiene fecha de vencimiento.')),
                ('dias_alerta_vencimiento', models.PositiveSmallIntegerField(default=30, help_text='Días antes del vencimiento para generar alerta.')),
                ('aplica_staff', models.BooleanField(default=True)),
                ('aplica_rco', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos', to='documentos.categoriadocumento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['categoria__orden', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='PDF, imagen u otro archivo del documento.', upload_to='documentos/%Y/%m/')),
                ('nombre_archivo', models.CharField(blank=True, help_text='Nombre descriptivo (se auto-genera si se deja vacío).', max_length=255)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Solo para documentos con vencimiento.', null=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('POR_VENCER', 'Por Vencer'), ('ANULADO', 'Anulado')], default='VIGENTE', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('version', models.PositiveSmallIntegerField(default=1, help_text='Versión del documento (incrementar al reemplazar).')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='personal.personal')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento del Trabajador',
                'verbose_name_plural': 'Documentos de Trabajadores',
                'ordering': ['-creado_en'],
            },
        ),
    ]
