# Generated by Django 5.1.15 on 2026-03-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaConstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Constancia de Trabajo', max_length=200)),
                ('codigo', models.SlugField(help_text='Código único (ej: constancia-trabajo). Se usa internamente.', unique=True)),
                ('categoria', models.CharField(choices=[('CONSTANCIA', 'Constancia'), ('CERTIFICADO', 'Certificado'), ('CARTA', 'Carta'), ('MEMO', 'Memorándum'), ('OTRO', 'Otro')], default='CONSTANCIA', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de uso.')),
                ('contenido_html', models.TextField(help_text='HTML con variables Django template. Use {{ personal.apellidos_nombres }}, etc.')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Constancia',
                'verbose_name_plural': 'Plantillas de Constancias',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
