# Generated by Django 5.1.15 on 2026-03-02 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_plantillaconstancia'),
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes de la boleta', verbose_name='Período')),
                ('tipo', models.CharField(choices=[('MENSUAL', 'Remuneración Mensual'), ('GRATIFICACION', 'Gratificación'), ('CTS', 'CTS'), ('LIQUIDACION', 'Liquidación'), ('UTILIDADES', 'Utilidades')], default='MENSUAL', max_length=15)),
                ('archivo', models.FileField(help_text='PDF de la boleta de pago', upload_to='boletas/%Y/%m/', verbose_name='Archivo PDF')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('remuneracion_bruta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rem. Bruta')),
                ('descuentos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuentos')),
                ('neto_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Neto a Pagar')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('LEIDA', 'Leída'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=12)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('ip_lectura', models.GenericIPAddressField(blank=True, null=True)),
                ('confirmada', models.BooleanField(default=False, help_text='Trabajador confirmó recepción de la boleta')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas_pago', to='personal.personal', verbose_name='Trabajador')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boleta de Pago',
                'verbose_name_plural': 'Boletas de Pago',
                'ordering': ['-periodo', 'personal__apellidos_nombres'],
                'indexes': [models.Index(fields=['personal', 'estado'], name='documentos__persona_bb1c49_idx'), models.Index(fields=['-periodo'], name='documentos__periodo_75586f_idx')],
                'unique_together': {('personal', 'periodo', 'tipo')},
            },
        ),
    ]
