# Generated by Django 5.1.15 on 2026-03-02 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_boletapago'),
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('REGLAMENTO', 'Reglamento Interno'), ('POLITICA', 'Política'), ('COMUNICADO', 'Comunicado'), ('MEMO', 'Memorándum'), ('CARTA', 'Carta Circular'), ('SST', 'Política SST'), ('OTRO', 'Otro')], default='COMUNICADO', max_length=20)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Resumen')),
                ('archivo', models.FileField(blank=True, help_text='Sube el documento en formato PDF o Word.', null=True, upload_to='documentos_laborales/%Y/%m/', verbose_name='Archivo (PDF/DOC)')),
                ('contenido_html', models.TextField(blank=True, help_text='Alternativo al archivo - se mostrará directamente en pantalla.', verbose_name='Contenido inline')),
                ('destinatarios_tipo', models.CharField(choices=[('TODOS', 'Todos los trabajadores'), ('STAFF', 'Solo STAFF'), ('RCO', 'Solo RCO'), ('AREA', 'Por Área(s)'), ('INDIVIDUAL', 'Individual')], default='TODOS', max_length=15, verbose_name='Destinatarios')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=15)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('requiere_confirmacion', models.BooleanField(default=True, help_text='El trabajador debe confirmar recepción del documento.', verbose_name='Requiere confirmación')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Fecha límite de vigencia del documento.', null=True, verbose_name='Vigente hasta')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(blank=True, help_text='Solo aplica cuando Destinatarios = Por Área(s).', related_name='docs_laborales', to='personal.area', verbose_name='Áreas destino')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personal_especifico', models.ManyToManyField(blank=True, help_text='Solo aplica cuando Destinatarios = Individual.', related_name='docs_laborales_individuales', to='personal.personal', verbose_name='Personal específico')),
            ],
            options={
                'verbose_name': 'Documento Laboral',
                'verbose_name_plural': 'Documentos Laborales',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EntregaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField(default=False)),
                ('fecha_visto', models.DateTimeField(blank=True, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('ip_confirmacion', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='documentos.documentolaboral')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_recibidos', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Entrega de Documento',
                'verbose_name_plural': 'Entregas de Documentos',
                'ordering': ['personal__apellidos_nombres'],
            },
        ),
        migrations.AddIndex(
            model_name='documentolaboral',
            index=models.Index(fields=['estado', '-creado_en'], name='documentos__estado_ecda45_idx'),
        ),
        migrations.AddIndex(
            model_name='entregadocumento',
            index=models.Index(fields=['personal', 'confirmado'], name='documentos__persona_7c93f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entregadocumento',
            unique_together={('documento', 'personal')},
        ),
    ]
