# Generated by Django 5.1.15 on 2026-03-02 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documentolaboral_entregadocumento_and_more'),
        ('personal', '0014_area_codigo_jefe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.SlugField(help_text='Identificador único (auto-generado).', max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('PROYECTO', 'Cierre de Proyecto'), ('LICITACION', 'Licitación / Concurso'), ('AUDITORIA', 'Auditoría'), ('CLIENTE', 'Entregable a Cliente'), ('INTERNO', 'Control Interno'), ('OTRO', 'Otro')], default='PROYECTO', max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Dossier',
                'verbose_name_plural': 'Plantillas de Dossier',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: "Dossier RRHH - Proyecto Expansión Norte Q1-2026"', max_length=250)),
                ('proyecto', models.CharField(blank=True, help_text='Nombre / código del proyecto u obra.', max_length=200)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('ENTREGADO', 'Entregado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=15)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_entrega_prevista', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_responsable', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(blank=True, help_text='Plantilla base. Puede dejarse vacía para armar ad-hoc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='documentos.plantilladossier')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaDossierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(blank=True, help_text='Sección o capítulo (ej: "I. Documentos de Identidad").', max_length=150)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('obligatorio', models.BooleanField(default=True, help_text='Si es obligatorio para esta plantilla (override por plantilla).')),
                ('instruccion', models.CharField(blank=True, help_text='Nota específica para este ítem (ej: "Vigente al momento de la obra").', max_length=300)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documentos.plantilladossier')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Ítem de Plantilla Dossier',
                'verbose_name_plural': 'Ítems de Plantilla Dossier',
                'ordering': ['orden', 'seccion'],
            },
        ),
        migrations.CreateModel(
            name='DossierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('seccion', models.CharField(blank=True, max_length=150)),
                ('obligatorio', models.BooleanField(default=True)),
                ('instruccion', models.CharField(blank=True, max_length=300)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETO', 'Completo'), ('OBSERVADO', 'Observado'), ('NO_APLICA', 'No Aplica')], default='PENDIENTE', max_length=15)),
                ('observacion', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(blank=True, help_text='Documento del legajo vinculado a este ítem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_items', to='documentos.documentotrabajador')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documentos.dossier')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='personal.personal')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Ítem de Dossier',
                'verbose_name_plural': 'Ítems de Dossier',
                'ordering': ['personal__apellidos_nombres', 'orden'],
                'indexes': [models.Index(fields=['dossier', 'estado'], name='documentos__dossier_df2db6_idx'), models.Index(fields=['dossier', 'personal'], name='documentos__dossier_99872b_idx')],
                'unique_together': {('dossier', 'personal', 'tipo_documento')},
            },
        ),
        migrations.CreateModel(
            name='DossierPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_dossier', to='documentos.dossier')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Personal del Dossier',
                'verbose_name_plural': 'Personal del Dossier',
                'ordering': ['personal__apellidos_nombres'],
                'unique_together': {('dossier', 'personal')},
            },
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['estado', '-creado_en'], name='documentos__estado_2e7f1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantilladossieritem',
            unique_together={('plantilla', 'tipo_documento')},
        ),
    ]
