# Generated by Django 5.1.15 on 2026-03-02 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_dossier_documentario'),
        ('personal', '0015_add_motivo_cese'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstanciaGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('ADMIN', 'Administración'), ('PORTAL', 'Portal del Trabajador')], default='ADMIN', max_length=10, verbose_name='Origen')),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constancias_generadas', to='personal.personal', verbose_name='Trabajador')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generaciones', to='documentos.plantillaconstancia', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Constancia Generada',
                'verbose_name_plural': 'Constancias Generadas',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['personal', '-fecha_generacion'], name='documentos__persona_337b41_idx'), models.Index(fields=['plantilla', '-fecha_generacion'], name='documentos__plantil_4f3574_idx')],
            },
        ),
    ]
