# Generated by Django 5.1.15 on 2026-03-04 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_add_constancia_generada'),
        ('personal', '0017_add_empresa_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFirmaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato de Trabajo'), ('ADENDA', 'Adenda / Modificacion'), ('CARTA', 'Carta'), ('MEMORANDUM', 'Memorandum'), ('ACTA', 'Acta'), ('CONFIDENCIAL', 'Acuerdo Confidencialidad'), ('RENUNCIA', 'Carta de Renuncia'), ('FINIQUITO', 'Finiquito / Liquidacion'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo_pdf', models.FileField(help_text='Sube el documento PDF que debe ser firmado.', upload_to='firma_digital/%Y/%m/', verbose_name='PDF a firmar')),
                ('zapsign_token', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Token ZapSign')),
                ('zapsign_doc_url', models.URLField(blank=True, verbose_name='URL documento ZapSign')),
                ('signer_token', models.CharField(blank=True, max_length=200, verbose_name='Token firmante')),
                ('signer_url', models.URLField(blank=True, verbose_name='URL para firmar')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente envio'), ('ENVIADO', 'Enviado a ZapSign'), ('FIRMANDO', 'En proceso de firma'), ('FIRMADO', 'Firmado completamente'), ('RECHAZADO', 'Rechazado por firmante'), ('VENCIDO', 'Link vencido'), ('CANCELADO', 'Cancelado'), ('ERROR', 'Error de envio')], default='PENDIENTE', max_length=15)),
                ('error_detalle', models.TextField(blank=True, verbose_name='Detalle del error')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('vence_en', models.DateField(blank=True, help_text='Fecha limite para firmar.', null=True)),
                ('pdf_firmado_url', models.URLField(blank=True, verbose_name='URL PDF firmado')),
                ('notas', models.TextField(blank=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_firma', to='personal.personal', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Documento para Firma Digital',
                'verbose_name_plural': 'Documentos para Firma Digital',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['personal', 'estado'], name='firma_personal_estado_idx'), models.Index(fields=['estado', 'creado_en'], name='firma_estado_fecha_idx')],
            },
        ),
    ]
