# Generated by Django 5.1.15 on 2026-03-29 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_add_archivohr_model'),
        ('personal', '0022_remove_personal_personal_fecha_alta_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CONSTANCIA', 'Constancia Generada'), ('DOCUMENTO', 'Documento del Trabajador'), ('LABORAL', 'Documento Laboral'), ('BOLETA', 'Boleta de Pago'), ('OTRO', 'Otro')], default='CONSTANCIA', max_length=20)),
                ('titulo_documento', models.CharField(blank=True, help_text='Titulo descriptivo del documento firmado.', max_length=300)),
                ('firma_imagen', models.TextField(blank=True, help_text='Imagen de la firma en base64 (data:image/png;base64,...)')),
                ('hash_documento', models.CharField(blank=True, db_index=True, help_text='SHA-256 del contenido del documento al momento de firmar.', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Direccion IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent del navegador')),
                ('token', models.CharField(db_index=True, help_text='Token unico para URL de firma.', max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de firma'), ('FIRMADO', 'Firmado'), ('RECHAZADO', 'Rechazado'), ('VENCIDO', 'Link vencido')], default='PENDIENTE', max_length=15)),
                ('solicitado_en', models.DateTimeField(auto_now_add=True)),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('vence_en', models.DateField(blank=True, help_text='Fecha limite para firmar.', null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Firma Digital (Interna)',
                'verbose_name_plural': 'Firmas Digitales (Internas)',
                'ordering': ['-solicitado_en'],
            },
        ),
        migrations.RenameIndex(
            model_name='archivohr',
            new_name='documentos__persona_424546_idx',
            old_name='documentos_archivohr_personal_idx',
        ),
        migrations.AddField(
            model_name='firmadigital',
            name='constancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas', to='documentos.constanciagenerada', verbose_name='Constancia (si aplica)'),
        ),
        migrations.AddField(
            model_name='firmadigital',
            name='documento_laboral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas', to='documentos.documentolaboral', verbose_name='Documento laboral (si aplica)'),
        ),
        migrations.AddField(
            model_name='firmadigital',
            name='documento_trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas', to='documentos.documentotrabajador', verbose_name='Documento del trabajador (si aplica)'),
        ),
        migrations.AddField(
            model_name='firmadigital',
            name='firmante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas_digitales', to='personal.personal', verbose_name='Firmante'),
        ),
        migrations.AddField(
            model_name='firmadigital',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddIndex(
            model_name='firmadigital',
            index=models.Index(fields=['firmante', 'estado'], name='documentos__firmant_f10260_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadigital',
            index=models.Index(fields=['token'], name='documentos__token_773771_idx'),
        ),
        migrations.AddIndex(
            model_name='firmadigital',
            index=models.Index(fields=['hash_documento'], name='documentos__hash_do_39d3a9_idx'),
        ),
    ]
