# Generated by Django 5.1.15 on 2026-03-02 03:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoViatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tope_diario', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo diario para este concepto. Vacío = sin tope.', max_digits=8, null=True, verbose_name='Tope Diario (S/)')),
                ('requiere_comprobante', models.BooleanField(default=True, help_text='Si requiere boleta/factura para la rendición')),
                ('afecto_renta', models.BooleanField(default=False, help_text='Si el exceso del tope es afecto a renta de 5ta categoría')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Concepto de Viático',
                'verbose_name_plural': 'Conceptos de Viático',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionViatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes al que corresponde la asignación', verbose_name='Período')),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Monto Asignado')),
                ('monto_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Reembolsos o ajustes al monto base', max_digits=10, verbose_name='Monto Adicional')),
                ('ubicacion', models.CharField(blank=True, help_text='Lugar de destino del trabajador', max_length=150, verbose_name='Ubicación/Proyecto')),
                ('dias_campo', models.PositiveSmallIntegerField(default=0, help_text='Días efectivos en campo para el período', verbose_name='Días en Campo')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('ENTREGADO', 'Entregado'), ('EN_RENDICION', 'En Rendición'), ('CONCILIADO', 'Conciliado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=15)),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('observaciones', models.TextField(blank=True)),
                ('monto_rendido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Rendido')),
                ('monto_devuelto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto que el trabajador devuelve a la empresa', max_digits=10, verbose_name='Monto Devuelto')),
                ('monto_reembolso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto que la empresa reembolsa al trabajador', max_digits=10, verbose_name='Monto a Reembolsar')),
                ('fecha_conciliacion', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaticos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaticos_creados', to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_viatico', to='personal.personal', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Asignación de Viático',
                'verbose_name_plural': 'Asignaciones de Viáticos',
                'ordering': ['-periodo', 'personal__apellidos_nombres'],
            },
        ),
        migrations.CreateModel(
            name='GastoViatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gasto', models.DateField(verbose_name='Fecha del Gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto (S/)')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('tipo_comprobante', models.CharField(choices=[('BOLETA', 'Boleta de Venta'), ('FACTURA', 'Factura'), ('RECIBO', 'Recibo por Honorarios'), ('TICKET', 'Ticket / Voucher'), ('DECLARACION', 'Declaración Jurada'), ('OTRO', 'Otro')], default='BOLETA', max_length=15, verbose_name='Tipo Comprobante')),
                ('numero_comprobante', models.CharField(blank=True, max_length=50, verbose_name='N° Comprobante')),
                ('ruc_proveedor', models.CharField(blank=True, max_length=11, verbose_name='RUC Proveedor')),
                ('archivo_comprobante', models.FileField(blank=True, null=True, upload_to='viaticos/comprobantes/%Y/%m/', verbose_name='Archivo Comprobante')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], default='PENDIENTE', max_length=12)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='viaticos.asignacionviatico', verbose_name='Asignación')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='viaticos.conceptoviatico', verbose_name='Concepto')),
            ],
            options={
                'verbose_name': 'Gasto de Viático',
                'verbose_name_plural': 'Gastos de Viáticos',
                'ordering': ['-fecha_gasto'],
            },
        ),
        migrations.AddIndex(
            model_name='asignacionviatico',
            index=models.Index(fields=['personal', 'estado'], name='viaticos_as_persona_4177c1_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionviatico',
            index=models.Index(fields=['-periodo'], name='viaticos_as_periodo_a7535a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionviatico',
            unique_together={('personal', 'periodo')},
        ),
        migrations.AddIndex(
            model_name='gastoviatico',
            index=models.Index(fields=['asignacion', 'estado'], name='viaticos_ga_asignac_da7085_idx'),
        ),
    ]
