# Generated by Django 5.1.15 on 2026-03-02 05:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('gravedad', models.CharField(choices=[('LEVE', 'Leve'), ('GRAVE', 'Grave'), ('MUY_GRAVE', 'Muy Grave')], default='LEVE', max_length=10)),
                ('base_legal', models.CharField(blank=True, help_text='Referencia legal (ej: DS 003-97-TR Art. 25 inc. a)', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Tipo de Falta',
                'verbose_name_plural': 'Tipos de Falta',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MedidaDisciplinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_medida', models.CharField(choices=[('VERBAL', 'Amonestación Verbal'), ('ESCRITA', 'Amonestación Escrita'), ('SUSPENSION', 'Suspensión'), ('DESPIDO', 'Despido')], max_length=12, verbose_name='Tipo de Medida')),
                ('fecha_hechos', models.DateField(verbose_name='Fecha de los Hechos')),
                ('descripcion_hechos', models.TextField(verbose_name='Descripción de los Hechos')),
                ('testigos', models.TextField(blank=True, help_text='Nombres de testigos presenciales', verbose_name='Testigos')),
                ('evidencias', models.FileField(blank=True, null=True, upload_to='disciplinaria/evidencias/%Y/%m/', verbose_name='Evidencias')),
                ('fecha_carta_preaviso', models.DateField(blank=True, help_text='Obligatoria para despido — inicia plazo de 6 días hábiles para descargo', null=True, verbose_name='Fecha Carta Preaviso')),
                ('documento_preaviso', models.FileField(blank=True, null=True, upload_to='disciplinaria/cartas/%Y/%m/', verbose_name='Carta de Preaviso')),
                ('fecha_limite_descargo', models.DateField(blank=True, help_text='6 días hábiles desde notificación (Art. 31 DS 003-97-TR)', null=True, verbose_name='Fecha Límite Descargo')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha Resolución')),
                ('resolucion', models.TextField(blank=True, help_text='Decisión final tras evaluar el descargo', verbose_name='Resolución')),
                ('dias_suspension', models.PositiveSmallIntegerField(default=0, help_text='Solo para tipo SUSPENSION', verbose_name='Días de Suspensión')),
                ('fecha_cese', models.DateField(blank=True, help_text='Solo para DESPIDO — fecha efectiva de cese', null=True, verbose_name='Fecha de Cese')),
                ('documento_resolucion', models.FileField(blank=True, null=True, upload_to='disciplinaria/resoluciones/%Y/%m/', verbose_name='Documento Resolución')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('NOTIFICADA', 'Notificada'), ('EN_DESCARGO', 'En Período de Descargo'), ('DESCARGO_RECIBIDO', 'Descargo Recibido'), ('RESUELTA', 'Resuelta'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas_disciplinarias', to='personal.personal', verbose_name='Trabajador')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas_registradas', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas_resueltas', to=settings.AUTH_USER_MODEL)),
                ('tipo_falta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medidas', to='disciplinaria.tipofalta', verbose_name='Tipo de Falta')),
            ],
            options={
                'verbose_name': 'Medida Disciplinaria',
                'verbose_name_plural': 'Medidas Disciplinarias',
                'ordering': ['-fecha_hechos'],
            },
        ),
        migrations.CreateModel(
            name='Descargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_presentacion', models.DateField(default=datetime.date.today, verbose_name='Fecha Presentación')),
                ('texto', models.TextField(verbose_name='Texto del Descargo')),
                ('archivos_adjuntos', models.FileField(blank=True, null=True, upload_to='disciplinaria/descargos/%Y/%m/', verbose_name='Adjuntos')),
                ('estado', models.CharField(choices=[('PRESENTADO', 'Presentado'), ('EN_REVISION', 'En Revisión'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PRESENTADO', max_length=15)),
                ('evaluacion', models.TextField(blank=True, help_text='Análisis del descargo por parte de HR/Legal', verbose_name='Evaluación')),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargos', to='personal.personal')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descargos_revisados', to=settings.AUTH_USER_MODEL)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargos', to='disciplinaria.medidadisciplinaria', verbose_name='Medida Disciplinaria')),
            ],
            options={
                'verbose_name': 'Descargo',
                'verbose_name_plural': 'Descargos',
                'ordering': ['-fecha_presentacion'],
            },
        ),
        migrations.AddIndex(
            model_name='medidadisciplinaria',
            index=models.Index(fields=['personal', 'estado'], name='disciplinar_persona_db7299_idx'),
        ),
        migrations.AddIndex(
            model_name='medidadisciplinaria',
            index=models.Index(fields=['-fecha_hechos'], name='disciplinar_fecha_h_325da4_idx'),
        ),
        migrations.AddIndex(
            model_name='medidadisciplinaria',
            index=models.Index(fields=['tipo_medida', 'estado'], name='disciplinar_tipo_me_1948cc_idx'),
        ),
    ]
