# Generated by Django 5.1.15 on 2026-03-02 05:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('CORE', 'Core / Organizacional'), ('LIDERAZGO', 'Liderazgo'), ('TECNICA', 'Técnica'), ('INTERPERSONAL', 'Interpersonal')], default='CORE', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CicloEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('90', 'Evaluación 90° (Jefe)'), ('180', 'Evaluación 180° (Jefe + Auto)'), ('360', 'Evaluación 360°'), ('OKR', 'Revisión OKR'), ('PRUEBA', 'Evaluación Periodo de Prueba')], default='180', max_length=10)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ABIERTO', 'Abierto'), ('EN_EVALUACION', 'En Evaluación'), ('CALIBRACION', 'En Calibración'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aplica_areas', models.ManyToManyField(blank=True, help_text='Vacío = aplica a todas las áreas', related_name='ciclos_evaluacion', to='personal.area', verbose_name='Áreas participantes')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ciclo de Evaluación',
                'verbose_name_plural': 'Ciclos de Evaluación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(choices=[('JEFE', 'Jefe Directo'), ('AUTO', 'Autoevaluación'), ('PAR', 'Par / Colega'), ('SUBORDINADO', 'Subordinado'), ('CLIENTE', 'Cliente Interno')], default='JEFE', max_length=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CALIBRADA', 'Calibrada')], default='PENDIENTE', max_length=12)),
                ('puntaje_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntaje Total')),
                ('puntaje_calibrado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntaje Calibrado')),
                ('comentario_general', models.TextField(blank=True, verbose_name='Comentarios Generales')),
                ('fortalezas', models.TextField(blank=True)),
                ('areas_mejora', models.TextField(blank=True, verbose_name='Áreas de Mejora')),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='evaluaciones.cicloevaluacion')),
                ('evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_recibidas', to='personal.personal')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_realizadas', to='personal.personal')),
                ('evaluador_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['evaluado__apellidos_nombres'],
            },
        ),
        migrations.CreateModel(
            name='PlanDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('objetivo', models.TextField(verbose_name='Objetivo del Plan')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=12)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes', to='evaluaciones.cicloevaluacion')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_desarrollo', to='personal.personal')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Seguimiento')),
            ],
            options={
                'verbose_name': 'Plan de Desarrollo Individual',
                'verbose_name_plural': 'Planes de Desarrollo',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AccionDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('CAPACITACION', 'Capacitación'), ('PROYECTO', 'Proyecto/Asignación'), ('MENTORIA', 'Mentoría'), ('LECTURA', 'Lectura/Estudio'), ('PRACTICA', 'Práctica'), ('OTRO', 'Otro')], default='CAPACITACION', max_length=15)),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite')),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='evaluaciones.plandesarrollo')),
            ],
            options={
                'verbose_name': 'Acción de Desarrollo',
                'verbose_name_plural': 'Acciones de Desarrollo',
                'ordering': ['fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Factor de ponderación', max_digits=5, verbose_name='Peso')),
                ('orden', models.PositiveSmallIntegerField(default=10)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.competencia')),
            ],
            options={
                'verbose_name': 'Competencia en Plantilla',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('escala_max', models.PositiveSmallIntegerField(default=5, help_text='Puntaje máximo por competencia (ej: 5)', verbose_name='Escala Máxima')),
                ('aplica_autoevaluacion', models.BooleanField(default=True)),
                ('aplica_jefe', models.BooleanField(default=True, verbose_name='Evaluación Jefe')),
                ('aplica_pares', models.BooleanField(default=False, verbose_name='Evaluación Pares')),
                ('aplica_subordinados', models.BooleanField(default=False, verbose_name='Evaluación Subordinados')),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('competencias', models.ManyToManyField(related_name='plantillas', through='evaluaciones.PlantillaCompetencia', to='evaluaciones.competencia')),
            ],
            options={
                'verbose_name': 'Plantilla de Evaluación',
                'verbose_name_plural': 'Plantillas de Evaluación',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='plantillacompetencia',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluaciones.plantillaevaluacion'),
        ),
        migrations.AddField(
            model_name='cicloevaluacion',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos', to='evaluaciones.plantillaevaluacion'),
        ),
        migrations.AlterUniqueTogether(
            name='plantillacompetencia',
            unique_together={('plantilla', 'competencia')},
        ),
        migrations.CreateModel(
            name='RespuestaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Puntaje')),
                ('comentario', models.TextField(blank=True)),
                ('competencia_plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.plantillacompetencia')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.evaluacion')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'unique_together': {('evaluacion', 'competencia_plantilla')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntaje Promedio')),
                ('puntaje_jefe', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('puntaje_auto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('puntaje_pares', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('clasificacion_desempeno', models.CharField(blank=True, choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=5, verbose_name='Desempeño')),
                ('clasificacion_potencial', models.CharField(blank=True, choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=5, verbose_name='Potencial')),
                ('nine_box_position', models.PositiveSmallIntegerField(blank=True, help_text='1-9 (1=bajo-bajo, 9=alto-alto)', null=True, verbose_name='Posición 9-Box')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_consolidacion', models.DateTimeField(blank=True, null=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='evaluaciones.cicloevaluacion')),
                ('consolidado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_evaluacion', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Resultado Consolidado',
                'verbose_name_plural': 'Resultados Consolidados',
                'ordering': ['-puntaje_promedio'],
                'unique_together': {('ciclo', 'personal')},
            },
        ),
    ]
