# Generated by Django 5.1.15 on 2026-03-02 15:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('personal', '0014_area_codigo_jefe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Objetivo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Contexto')),
                ('nivel', models.CharField(choices=[('EMPRESA', 'Empresa'), ('AREA', 'Área'), ('INDIVIDUAL', 'Individual')], default='INDIVIDUAL', max_length=12)),
                ('periodo', models.CharField(choices=[('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='TRIMESTRAL', max_length=12)),
                ('anio', models.SmallIntegerField(default=2026, verbose_name='Año')),
                ('trimestre', models.SmallIntegerField(blank=True, help_text='Solo para períodos trimestrales.', null=True, verbose_name='Trimestre (1-4)')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('EN_RIESGO', 'En Riesgo'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=12)),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Importancia relativa dentro del período (suma debería ser 100%).', max_digits=5, verbose_name='Peso (%)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, help_text='Para objetivos de área o empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='okrs', to='personal.area', verbose_name='Área')),
                ('ciclo_evaluacion', models.ForeignKey(blank=True, help_text='Si aplica, vincula este OKR a un ciclo de evaluación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='okrs', to='evaluaciones.cicloevaluacion', verbose_name='Ciclo de evaluación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('objetivo_padre', models.ForeignKey(blank=True, help_text='Objetivo de nivel superior al que contribuye este objetivo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_hijo', to='evaluaciones.objetivoclave', verbose_name='Objetivo padre')),
                ('personal', models.ForeignKey(blank=True, help_text='Solo para objetivos individuales.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='okrs', to='personal.personal', verbose_name='Responsable (individual)')),
            ],
            options={
                'verbose_name': 'Objetivo Clave (OKR)',
                'verbose_name_plural': 'Objetivos Clave (OKR)',
                'ordering': ['-anio', 'trimestre', 'nivel', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Resultado Clave')),
                ('unidad', models.CharField(choices=[('PORCENTAJE', '%'), ('NUMERO', 'Número'), ('MONEDA', 'S/'), ('SI_NO', 'Sí / No'), ('PUNTOS', 'Puntos (0-10)'), ('DIAS', 'Días'), ('HORAS', 'Horas'), ('PERSONALIZADO', 'Personalizado')], default='PORCENTAJE', max_length=15)),
                ('unidad_personalizada', models.CharField(blank=True, help_text='Solo si unidad = Personalizado (ej: "clientes", "tickets").', max_length=30)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('completado_binario', models.BooleanField(default=False, help_text='Para KRs de tipo Sí/No.')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_clave', to='evaluaciones.objetivoclave')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='krs_responsable', to='personal.personal', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Resultado Clave (KR)',
                'verbose_name_plural': 'Resultados Clave (KR)',
                'ordering': ['orden', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='CheckInOKR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de actualización')),
                ('valor_nuevo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor actualizado')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario / Bloqueos')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resultado_clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='evaluaciones.resultadoclave')),
            ],
            options={
                'verbose_name': 'Check-in OKR',
                'verbose_name_plural': 'Check-ins OKR',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='objetivoclave',
            index=models.Index(fields=['anio', 'trimestre', 'status'], name='evaluacione_anio_9e11ad_idx'),
        ),
        migrations.AddIndex(
            model_name='objetivoclave',
            index=models.Index(fields=['personal', 'status'], name='evaluacione_persona_7833ca_idx'),
        ),
    ]
