# Generated by Django 5.1.15 on 2026-03-04 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='fa-code-branch', max_length=50)),
                ('campo_trigger', models.CharField(default='estado', max_length=50)),
                ('valor_trigger', models.CharField(max_length=100)),
                ('campo_resultado', models.CharField(default='estado', max_length=50)),
                ('valor_aprobado', models.CharField(default='Aprobado', max_length=100)),
                ('valor_rechazado', models.CharField(default='Rechazado', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('notificar_email', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Modelo Django que activa este flujo (ej: SolicitudVacacion)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Flujo de Trabajo',
                'verbose_name_plural': 'Flujos de Trabajo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EtapaFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('nombre', models.CharField(help_text='Ej: Aprobacion Jefe Inmediato', max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_aprobador', models.CharField(choices=[('SUPERUSER', 'Cualquier administrador RRHH'), ('USUARIO', 'Usuario especifico'), ('JEFE_AREA', 'Jefe del area del solicitante'), ('GRUPO_DJANGO', 'Grupo de Django (rol)')], default='SUPERUSER', max_length=20)),
                ('tiempo_limite_horas', models.PositiveIntegerField(default=72, help_text='Horas antes de aplicar la accion por vencimiento (0 = sin limite)')),
                ('accion_vencimiento', models.CharField(choices=[('ESPERAR', 'No tomar accion (esperar)'), ('AUTO_APROBAR', 'Auto-aprobar al vencer'), ('AUTO_RECHAZAR', 'Auto-rechazar al vencer'), ('ESCALAR', 'Escalar a usuario alterno')], default='ESPERAR', max_length=15)),
                ('requiere_comentario', models.BooleanField(default=False)),
                ('notificar_solicitante_al_decidir', models.BooleanField(default=True)),
                ('aprobador_grupo', models.ForeignKey(blank=True, help_text='Solo si tipo_aprobador = GRUPO_DJANGO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('aprobador_usuario', models.ForeignKey(blank=True, help_text='Solo si tipo_aprobador = USUARIO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_como_aprobador', to=settings.AUTH_USER_MODEL)),
                ('escalar_a', models.ForeignKey(blank=True, help_text='Solo si accion_vencimiento = ESCALAR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='workflows.flujotrabajo')),
            ],
            options={
                'verbose_name': 'Etapa de Flujo',
                'verbose_name_plural': 'Etapas de Flujo',
                'ordering': ['flujo', 'orden'],
                'unique_together': {('flujo', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='InstanciaFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido')], db_index=True, default='EN_PROCESO', max_length=15)),
                ('object_id', models.PositiveIntegerField()),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('etapa_vence_en', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('etapa_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias_en_esta_etapa', to='workflows.etapaflujo')),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='workflows.flujotrabajo')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instancia de Flujo',
                'verbose_name_plural': 'Instancias de Flujo',
                'ordering': ['-iniciado_en'],
            },
        ),
        migrations.CreateModel(
            name='PasoFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('DELEGADO', 'Delegado'), ('AUTO_APROBADO', 'Auto-aprobado (timeout)'), ('AUTO_RECHAZADO', 'Auto-rechazado (timeout)'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aprobador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.etapaflujo')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='workflows.instanciaflujo')),
            ],
            options={
                'verbose_name': 'Paso de Flujo',
                'verbose_name_plural': 'Pasos de Flujo',
                'ordering': ['instancia', 'fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='instanciaflujo',
            index=models.Index(fields=['estado', 'iniciado_en'], name='wf_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='instanciaflujo',
            index=models.Index(fields=['content_type', 'object_id'], name='wf_objeto_idx'),
        ),
    ]
