# Generated by Django 5.1.15 on 2026-03-01 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto — datos en edición'), ('EN_CIERRE', 'En Cierre — wizard en progreso'), ('CERRADO', 'Cerrado — período bloqueado'), ('REABIERTO', 'Reabierto — revisión post-cierre')], default='ABIERTO', max_length=12, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Período de Cierre',
                'verbose_name_plural': 'Períodos de Cierre',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='PasoCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('VERIFICAR_IMPORTACIONES', 'Verificar importaciones del período'), ('VALIDAR_DNI', 'Validar registros sin match de DNI'), ('VERIFICAR_SS', 'Verificar consistencia Sin Salida'), ('ASEGURAR_BANCO', 'Asegurar BancoHoras STAFF activo'), ('GENERAR_CARGA_S10', 'Generar Carga S10 para RCO'), ('REPORTE_CIERRE', 'Generar reporte de cierre'), ('BLOQUEAR_PERIODO', 'Bloquear período')], max_length=40)),
                ('orden', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EJECUTANDO', 'Ejecutando...'), ('OK', 'Completado'), ('ERROR', 'Error'), ('ADVERTENCIA', 'Advertencia'), ('OMITIDO', 'Omitido')], default='PENDIENTE', max_length=12)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('ejecutado_en', models.DateTimeField(blank=True, null=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='cierre.periodocierre')),
            ],
            options={
                'verbose_name': 'Paso de Cierre',
                'verbose_name_plural': 'Pasos de Cierre',
                'ordering': ['orden'],
                'unique_together': {('periodo', 'codigo')},
            },
        ),
    ]
