# Generated by Django 5.1.15 on 2026-03-02 16:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0014_area_codigo_jefe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoRemunerativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('DESCUENTO', 'Descuento trabajador'), ('APORTE_EMPLEADOR', 'Aporte empleador')], max_length=20)),
                ('subtipo', models.CharField(choices=[('REMUNERATIVO', 'Remunerativo'), ('NO_REMUNERATIVO', 'No remunerativo'), ('PROVISION', 'Provisión (Gratif/CTS)')], default='REMUNERATIVO', max_length=20)),
                ('formula', models.CharField(choices=[('FIJO', 'Monto fijo'), ('PORCENTAJE', 'Porcentaje de remuneración computable'), ('DIAS_TRABAJADOS', 'Proporcional a días trabajados (sueldo base)'), ('HE_25', 'Horas extra 25%'), ('HE_35', 'Horas extra 35%'), ('HE_100', 'Horas extra 100%'), ('AFP_APORTE', 'AFP — Aporte obligatorio 10%'), ('AFP_COMISION', 'AFP — Comisión flujo'), ('AFP_SEGURO', 'AFP — Prima de seguro'), ('ONP', 'ONP — Sistema Nacional 13%'), ('ESSALUD', 'EsSalud — Aporte empleador 9%'), ('IR_5TA', 'IR 5ta categoría (retención)'), ('GRATIFICACION', 'Gratificación (julio/dic)'), ('CTS', 'CTS (mayo/nov)'), ('MANUAL', 'Entrada manual')], default='FIJO', max_length=20)),
                ('porcentaje', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Para fórmula PORCENTAJE: valor en %. Ej: 10 = 10%', max_digits=7)),
                ('afecto_essalud', models.BooleanField(default=False)),
                ('afecto_renta', models.BooleanField(default=False)),
                ('afecto_cts', models.BooleanField(default=False)),
                ('afecto_gratif', models.BooleanField(default=False)),
                ('es_sistema', models.BooleanField(default=False, help_text='Protegido — no eliminar.')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Concepto Remunerativo',
                'verbose_name_plural': 'Conceptos Remunerativos',
                'ordering': ['tipo', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REGULAR', 'Planilla Regular'), ('GRATIFICACION', 'Gratificación'), ('CTS', 'CTS'), ('UTILIDADES', 'Utilidades'), ('LIQUIDACION', 'Liquidación')], default='REGULAR', max_length=15)),
                ('anio', models.SmallIntegerField()),
                ('mes', models.SmallIntegerField(help_text='1-12')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CALCULADO', 'Calculado'), ('APROBADO', 'Aprobado'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=12)),
                ('total_trabajadores', models.SmallIntegerField(default=0)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_neto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_costo_empresa', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Neto + EsSalud + SCTR empleador', max_digits=14)),
                ('generado_en', models.DateTimeField(blank=True, null=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Período de Nómina',
                'verbose_name_plural': 'Períodos de Nómina',
                'ordering': ['-anio', '-mes', 'tipo'],
                'unique_together': {('tipo', 'anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='RegistroNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('regimen_pension', models.CharField(default='AFP', max_length=12)),
                ('afp', models.CharField(blank=True, max_length=20)),
                ('grupo', models.CharField(blank=True, max_length=10)),
                ('dias_trabajados', models.SmallIntegerField(default=30)),
                ('dias_descanso', models.SmallIntegerField(default=0)),
                ('dias_falta', models.SmallIntegerField(default=0)),
                ('horas_extra_25', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('horas_extra_35', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('horas_extra_100', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('asignacion_familiar', models.BooleanField(default=False)),
                ('descuento_prestamo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('otros_ingresos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('neto_a_pagar', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('aporte_essalud', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('costo_total_empresa', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('estado', models.CharField(choices=[('CALCULADO', 'Calculado'), ('REVISADO', 'Revisado'), ('APROBADO', 'Aprobado'), ('OBSERVADO', 'Observado')], default='CALCULADO', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='nominas.periodonomina')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Registro de Nómina',
                'verbose_name_plural': 'Registros de Nómina',
                'ordering': ['personal__apellidos_nombres'],
                'unique_together': {('periodo', 'personal')},
            },
        ),
        migrations.CreateModel(
            name='LineaNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_calculo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nominas.conceptoremunerativo')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='nominas.registronomina')),
            ],
            options={
                'verbose_name': 'Línea de Nómina',
                'verbose_name_plural': 'Líneas de Nómina',
                'ordering': ['concepto__tipo', 'concepto__orden'],
            },
        ),
    ]
