# Generated by Django 5.1.15 on 2026-03-04 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('nominas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodonomina',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_nomina', to='empresas.empresa', verbose_name='Empresa'),
        ),
    ]
