# Generated by Django 5.1.15 on 2026-03-05 03:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('nominas', '0003_add_presupuesto_planilla'),
        ('personal', '0020_add_cond_trabajo_alimentacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Plan')),
                ('tipo', models.CharField(choices=[('OBRA', 'Obra / Proyecto'), ('EMPRESA', 'Empresa / Área')], max_length=10)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Alcance')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio del horizonte')),
                ('fecha_fin', models.DateField(blank=True, help_text='Vacío = indefinido. Para OBRA es obligatorio.', null=True, verbose_name='Fin del horizonte')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('VIGENTE', 'Vigente'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, help_text='Para EMPRESA: área/departamento que administra el plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='personal.area', verbose_name='Área responsable')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_plantilla', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Plan de Plantilla',
                'verbose_name_plural': 'Planes de Plantilla',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LineaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo / Puesto')),
                ('cantidad', models.PositiveSmallIntegerField(default=1, help_text='Número de personas para este cargo en el plan.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='N° de posiciones')),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Sueldo base (por persona)')),
                ('asignacion_familiar', models.BooleanField(default=False, verbose_name='Asignación familiar')),
                ('regimen_pension', models.CharField(choices=[('AFP', 'AFP'), ('ONP', 'ONP'), ('SIN_PENSION', 'Sin Régimen')], default='AFP', max_length=12)),
                ('afp', models.CharField(blank=True, choices=[('Habitat', 'Habitat'), ('Integra', 'Integra'), ('Prima', 'Prima'), ('Profuturo', 'Profuturo')], help_text='Solo si régimen es AFP.', max_length=20)),
                ('cond_trabajo_mensual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cond. Trabajo / Hospedaje (mensual, por persona)')),
                ('alimentacion_mensual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Alimentación (mensual, por persona)')),
                ('fecha_inicio_puesto', models.DateField(verbose_name='Inicio del puesto')),
                ('fecha_fin_puesto', models.DateField(blank=True, help_text='Vacío = hasta el fin del plan.', null=True, verbose_name='Fin del puesto')),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='personal.area', verbose_name='Área')),
                ('personal', models.ForeignKey(blank=True, help_text='Si ya se sabe quién ocupa el puesto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_plan', to='personal.personal', verbose_name='Persona asignada (opcional)')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='nominas.planplantilla')),
            ],
            options={
                'verbose_name': 'Línea de Plan',
                'verbose_name_plural': 'Líneas de Plan',
                'ordering': ['orden', 'cargo'],
            },
        ),
    ]
