# Generated by Django 5.1.15 on 2026-04-02 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_cargo_model_plantilla_evolution'),
        ('nominas', '0005_add_missing_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='periodonomina',
            name='periodonomina_estado_idx',
        ),
        migrations.RemoveIndex(
            model_name='periodonomina',
            name='periodonomina_anio_mes_idx',
        ),
        migrations.RemoveIndex(
            model_name='registronomina',
            name='registronomina_personal_idx',
        ),
        migrations.RemoveIndex(
            model_name='registronomina',
            name='registronomina_estado_idx',
        ),
        migrations.RemoveIndex(
            model_name='registronomina',
            name='registronomina_periodo_est_idx',
        ),
        migrations.AlterUniqueTogether(
            name='periodonomina',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='periodonomina',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'LIQUIDACION'), _negated=True), fields=('tipo', 'anio', 'mes'), name='nominas_periodo_unique_no_liquidacion'),
        ),
    ]
