# Generated by Django 5.1.15 on 2026-04-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0006_unique_constraint_no_liquidacion'),
        ('nominas', '0007_recargaalimentacion'),
    ]

    operations = [
    ]
