# Generated by Django 5.1.15 on 2026-04-14 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0006_recargaalimentacion'),
        ('nominas', '0008_merge_20260413_2247'),
    ]

    operations = [
    ]
