# Generated by Django 5.1.15 on 2026-03-02 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('T_REGISTRO_ALTA', 'T-Registro — Altas'), ('T_REGISTRO_BAJA', 'T-Registro — Bajas'), ('T_REGISTRO_MODIF', 'T-Registro — Modificaciones'), ('PLAME', 'PDT PLAME'), ('AFP_NET', 'AFP Net — Aportes'), ('BANCO_BCP', 'Banco BCP — Telecrédito'), ('BANCO_BBVA', 'Banco BBVA — Pagos'), ('BANCO_IBK', 'Banco Interbank — Pagos'), ('BANCO_SCO', 'Banco Scotiabank — Pagos'), ('BANCO_NACION', 'Banco de la Nación — Pagos'), ('ESSALUD', 'ESSALUD — Declaración'), ('PLANILLA_EXCEL', 'Planilla Excel resumen'), ('OTRO', 'Otro')], max_length=20)),
                ('periodo', models.CharField(blank=True, help_text='Período en formato YYYY-MM (ej: 2026-03)', max_length=7)),
                ('estado', models.CharField(choices=[('OK', 'Exitoso'), ('ERROR', 'Error'), ('PARCIAL', 'Parcial')], default='OK', max_length=10)),
                ('registros', models.PositiveIntegerField(default=0, help_text='Cantidad de registros exportados')),
                ('nombre_archivo', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Exportación',
                'verbose_name_plural': 'Logs de Exportación',
                'ordering': ['-generado_en'],
            },
        ),
    ]
