# Generated by Django 5.1.15 on 2026-03-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logexportacion',
            name='tipo',
            field=models.CharField(choices=[('T_REGISTRO_ALTA', 'T-Registro — Altas'), ('T_REGISTRO_BAJA', 'T-Registro — Bajas'), ('T_REGISTRO_MODIF', 'T-Registro — Modificaciones'), ('PLAME', 'PDT PLAME'), ('AFP_NET', 'AFP Net — Aportes'), ('BANCO_BCP', 'Banco BCP — Telecrédito'), ('BANCO_BBVA', 'Banco BBVA — Pagos'), ('BANCO_IBK', 'Banco Interbank — Pagos'), ('BANCO_SCO', 'Banco Scotiabank — Pagos'), ('BANCO_NACION', 'Banco de la Nación — Pagos'), ('ESSALUD', 'ESSALUD — Declaración'), ('PLANILLA_EXCEL', 'Planilla Excel resumen'), ('CONCAR', 'Asiento CONCAR'), ('SIGO', 'Asiento SIGO / Softpyme'), ('SAP_EXCEL', 'Asiento SAP Excel (BAPI FB50)'), ('SIRE_PLE', 'SIRE PLE 5.1 — Libro Diario'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
