# Generated by Django 5.1.15 on 2026-03-04 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0002_add_contable_tipos'),
        ('reclutamiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPublicacionVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('COMPUTRABAJO', 'Computrabajo Peru'), ('BUMERAN', 'Bumeran Peru'), ('LINKEDIN', 'LinkedIn Jobs'), ('PORTAL', 'Portal de Empleo Propio')], max_length=15, verbose_name='Plataforma')),
                ('estado', models.CharField(choices=[('OK', 'Exitoso'), ('ERROR', 'Error')], default='OK', max_length=5, verbose_name='Estado')),
                ('url_publicada', models.URLField(blank=True, help_text='URL de la oferta en la plataforma externa (si aplica)', verbose_name='URL Publicada')),
                ('respuesta_api', models.TextField(blank=True, help_text='JSON o mensaje de respuesta devuelto por la plataforma', verbose_name='Respuesta API')),
                ('mensaje', models.TextField(blank=True, help_text='Mensaje de exito o descripcion del error', verbose_name='Mensaje')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_publicacion', to='reclutamiento.vacante', verbose_name='Vacante')),
            ],
            options={
                'verbose_name': 'Log de Publicacion de Vacante',
                'verbose_name_plural': 'Logs de Publicacion de Vacantes',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['vacante', 'plataforma'], name='integracion_vacante_d67d1b_idx'), models.Index(fields=['-creado_en'], name='integracion_creado__6b7e53_idx')],
            },
        ),
    ]
