# Generated by Django 5.1.15 on 2026-03-02 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandaSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('nivel', models.CharField(choices=[('JUNIOR', 'Junior'), ('SEMI_SENIOR', 'Semi Senior'), ('SENIOR', 'Senior'), ('LEAD', 'Lead'), ('GERENTE', 'Gerente')], max_length=12, verbose_name='Nivel')),
                ('minimo', models.DecimalField(decimal_places=2, help_text='Límite inferior de la banda salarial', max_digits=10, verbose_name='Mínimo')),
                ('medio', models.DecimalField(decimal_places=2, help_text='Punto medio de referencia para compa-ratio', max_digits=10, verbose_name='Medio (Midpoint)')),
                ('maximo', models.DecimalField(decimal_places=2, help_text='Límite superior de la banda salarial', max_digits=10, verbose_name='Máximo')),
                ('moneda', models.CharField(choices=[('PEN', 'Sol (S/)'), ('USD', 'Dólar (US$)')], default='PEN', max_length=3, verbose_name='Moneda')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banda Salarial',
                'verbose_name_plural': 'Bandas Salariales',
                'ordering': ['cargo', 'nivel'],
                'indexes': [models.Index(fields=['cargo', 'nivel'], name='salarios_ba_cargo_c3f905_idx'), models.Index(fields=['activa'], name='salarios_ba_activa_de431e_idx')],
                'unique_together': {('cargo', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='SimulacionIncremento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Simulación')),
                ('fecha', models.DateField(verbose_name='Fecha de Simulación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('APLICADA', 'Aplicada')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto Fijo')], default='PORCENTAJE', max_length=12, verbose_name='Tipo de Incremento')),
                ('presupuesto_total', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto máximo disponible para esta simulación', max_digits=12, null=True, verbose_name='Presupuesto Total')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Simulación de Incremento',
                'verbose_name_plural': 'Simulaciones de Incremento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remuneracion_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Remuneración Actual')),
                ('incremento_propuesto', models.DecimalField(decimal_places=2, help_text='Monto del incremento (no el nuevo sueldo)', max_digits=10, verbose_name='Incremento Propuesto')),
                ('aprobado', models.BooleanField(default=True, help_text='Marcar si este incremento individual fue aprobado', verbose_name='Aprobado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulaciones_detalle', to='personal.personal', verbose_name='Trabajador')),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='salarios.simulacionincremento', verbose_name='Simulación')),
            ],
            options={
                'verbose_name': 'Detalle de Simulación',
                'verbose_name_plural': 'Detalles de Simulación',
                'ordering': ['personal__apellidos_nombres'],
            },
        ),
        migrations.CreateModel(
            name='HistorialSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_efectiva', models.DateField(verbose_name='Fecha Efectiva')),
                ('remuneracion_anterior', models.DecimalField(decimal_places=2, help_text='Sueldo base antes del cambio', max_digits=10, verbose_name='Remuneración Anterior')),
                ('remuneracion_nueva', models.DecimalField(decimal_places=2, help_text='Sueldo base después del cambio', max_digits=10, verbose_name='Remuneración Nueva')),
                ('motivo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('INCREMENTO', 'Incremento Anual'), ('PROMOCION', 'Promoción'), ('AJUSTE', 'Ajuste de Mercado'), ('REVALORACION', 'Revalorización')], max_length=15, verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incrementos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_salarial', to='personal.personal', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Historial Salarial',
                'verbose_name_plural': 'Historial Salarial',
                'ordering': ['-fecha_efectiva'],
                'indexes': [models.Index(fields=['personal', '-fecha_efectiva'], name='salarios_hi_persona_f9a33d_idx'), models.Index(fields=['-fecha_efectiva'], name='salarios_hi_fecha_e_91accb_idx'), models.Index(fields=['motivo'], name='salarios_hi_motivo_ca23c5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='simulacionincremento',
            index=models.Index(fields=['-fecha'], name='salarios_si_fecha_a9eb57_idx'),
        ),
        migrations.AddIndex(
            model_name='simulacionincremento',
            index=models.Index(fields=['estado'], name='salarios_si_estado_e6d58d_idx'),
        ),
        migrations.AddIndex(
            model_name='detallesimulacion',
            index=models.Index(fields=['simulacion', 'personal'], name='salarios_de_simulac_26e07c_idx'),
        ),
        migrations.AddIndex(
            model_name='detallesimulacion',
            index=models.Index(fields=['aprobado'], name='salarios_de_aprobad_014983_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallesimulacion',
            unique_together={('simulacion', 'personal')},
        ),
    ]
