# Generated by Django 5.1.15 on 2026-02-25 17:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personal", "0010_alter_area_responsables"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeriadoCalendario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fecha", models.DateField(unique=True, verbose_name="Fecha del Feriado")),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre del Feriado")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NO_RECUPERABLE", "Feriado No Recuperable (remunerado)"),
                            ("RECUPERABLE", "Feriado Recuperable"),
                            ("PUENTE", "Puente / Decreto"),
                        ],
                        default="NO_RECUPERABLE",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Feriado",
                "verbose_name_plural": "Feriados",
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="HomologacionCodigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codigo_origen",
                    models.CharField(
                        help_text="Ej: 'B', 'V', 'SS', 'DM', '>0' para cualquier número positivo",
                        max_length=20,
                        unique=True,
                        verbose_name="Código Origen (sistema asistencia)",
                    ),
                ),
                (
                    "codigo_tareo",
                    models.CharField(
                        help_text="Ej: 'DL', 'VAC', 'A', 'F', 'DM'",
                        max_length=20,
                        verbose_name="Código Tareo (interno)",
                    ),
                ),
                (
                    "codigo_roster",
                    models.CharField(
                        blank=True,
                        help_text="Vacío si no aplica cruce con roster",
                        max_length=20,
                        verbose_name="Código Roster (para cruce Fase 2)",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200, verbose_name="Descripción")),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("ASISTENCIA", "Asistencia efectiva"),
                            ("AUSENCIA", "Ausencia no justificada (Falta)"),
                            ("PERMISO", "Permiso / Licencia"),
                            ("DESCANSO", "Descanso del ciclo / DL"),
                            ("VACACIONES", "Vacaciones"),
                            ("SUSPENSION", "Suspensión disciplinaria"),
                            ("FERIADO", "Feriado"),
                            ("FERIADO_LABORADO", "Feriado laborado"),
                            ("TELETRABAJO", "Trabajo remoto"),
                            ("COMPENSACION", "Compensación de horas"),
                            ("DESCANSO_MEDICO", "Descanso médico"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Evento",
                    ),
                ),
                (
                    "signo",
                    models.CharField(
                        choices=[
                            ("+", "Suma (cuenta como día trabajado / hábil)"),
                            ("-", "Resta (descuenta remuneración o no cuenta)"),
                            ("N", "Neutral (no suma ni resta)"),
                        ],
                        default="+",
                        max_length=1,
                        verbose_name="Signo (impacto remunerativo)",
                    ),
                ),
                (
                    "cuenta_asistencia",
                    models.BooleanField(default=True, verbose_name="¿Cuenta como asistencia?"),
                ),
                (
                    "genera_he",
                    models.BooleanField(
                        default=False,
                        help_text="True para asistencias donde el exceso de horas sea HE",
                        verbose_name="¿Puede generar HE?",
                    ),
                ),
                (
                    "es_numerico",
                    models.BooleanField(
                        default=False, verbose_name="¿El valor origen es numérico (horas)?"
                    ),
                ),
                (
                    "prioridad",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="1=Papeleta > 5=Feriado > 10=Reloj > 99=Falta por defecto",
                        verbose_name="Prioridad",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Homologación de Código",
                "verbose_name_plural": "Homologaciones de Código",
                "ordering": ["prioridad", "codigo_origen"],
            },
        ),
        migrations.CreateModel(
            name="RegimenTurno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: '21x7 Foráneo', '5x2 Local', 'Turno Noche'",
                        max_length=60,
                        unique=True,
                        verbose_name="Nombre del Régimen",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Ej: 21X7, 5X2, TN",
                        max_length=10,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "jornada_tipo",
                    models.CharField(
                        choices=[
                            ("ACUMULATIVA", "Jornada Acumulativa / Atípica (Art. 9 DS 007-2002)"),
                            ("SEMANAL", "Jornada Semanal Fija (máx. 48 h/semana)"),
                            ("ROTATIVA", "Turno Rotativo (descanso no fijo)"),
                            ("NOCTURNA", "Turno Nocturno (+35% recargo mínimo legal)"),
                            ("ESPECIAL", "Régimen Especial (configuración manual)"),
                        ],
                        default="SEMANAL",
                        max_length=15,
                        verbose_name="Tipo de Jornada",
                    ),
                ),
                (
                    "dias_trabajo_ciclo",
                    models.PositiveSmallIntegerField(
                        help_text="Ej: 21 para régimen 21×7",
                        verbose_name="Días de Trabajo por Ciclo",
                    ),
                ),
                (
                    "dias_descanso_ciclo",
                    models.PositiveSmallIntegerField(
                        help_text="Ej: 7 para régimen 21×7",
                        verbose_name="Días de Descanso por Ciclo",
                    ),
                ),
                (
                    "minutos_almuerzo",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="Descontados del tiempo bruto para calcular horas efectivas",
                        verbose_name="Minutos de Almuerzo",
                    ),
                ),
                (
                    "es_nocturno",
                    models.BooleanField(
                        default=False,
                        help_text="Activa recargo mínimo del 35% sobre RMV",
                        verbose_name="¿Es Turno Nocturno?",
                    ),
                ),
                (
                    "recargo_nocturno_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("35.00"),
                        help_text="Porcentaje mínimo legal 35%; puede ser mayor por negociación",
                        max_digits=5,
                        verbose_name="% Recargo Nocturno",
                    ),
                ),
                ("descripcion", models.TextField(blank=True, verbose_name="Descripción / Notas")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Régimen de Turno",
                "verbose_name_plural": "Regímenes de Turno",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="BancoHoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("periodo_anio", models.PositiveSmallIntegerField(verbose_name="Año")),
                (
                    "periodo_mes",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mes",
                    ),
                ),
                (
                    "he_25_acumuladas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=7,
                        verbose_name="HE 25% Acumuladas (h)",
                    ),
                ),
                (
                    "he_35_acumuladas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=7,
                        verbose_name="HE 35% Acumuladas (h)",
                    ),
                ),
                (
                    "he_100_acumuladas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=7,
                        verbose_name="HE 100% Acumuladas (feriado, h)",
                    ),
                ),
                (
                    "he_compensadas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=7,
                        verbose_name="HE Compensadas (h usadas como CHE/descanso)",
                    ),
                ),
                (
                    "saldo_horas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total acumuladas − compensadas",
                        max_digits=7,
                        verbose_name="Saldo al Cierre del Período",
                    ),
                ),
                (
                    "cerrado",
                    models.BooleanField(
                        default=False,
                        help_text="True cuando fue auditado y no puede modificarse",
                        verbose_name="Período Cerrado",
                    ),
                ),
                ("observaciones", models.TextField(blank=True, verbose_name="Observaciones")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banco_horas",
                        to="personal.personal",
                        verbose_name="Personal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banco de Horas",
                "verbose_name_plural": "Banco de Horas",
                "ordering": ["-periodo_anio", "-periodo_mes", "personal"],
            },
        ),
        migrations.CreateModel(
            name="RegistroPapeleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dni", models.CharField(max_length=20, verbose_name="DNI/Doc")),
                (
                    "nombre_archivo",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Nombre (del archivo)"
                    ),
                ),
                (
                    "tipo_permiso",
                    models.CharField(
                        choices=[
                            ("COMPENSACION_HE", "Compensación por Horario Extendido (CHE)"),
                            ("BAJADAS", "Bajadas / Día Libre (DL)"),
                            ("BAJADAS_ACUMULADAS", "Bajadas Acumuladas (DLA)"),
                            ("VACACIONES", "Vacaciones (VAC)"),
                            ("DESCANSO_MEDICO", "Descanso Médico (DM)"),
                            ("LICENCIA_CON_GOCE", "Licencia con Goce (LCG)"),
                            ("LICENCIA_SIN_GOCE", "Licencia sin Goce (LSG)"),
                            ("LICENCIA_FALLECIMIENTO", "Licencia por Fallecimiento (LF)"),
                            ("LICENCIA_PATERNIDAD", "Licencia por Paternidad (LP)"),
                            ("COMISION_TRABAJO", "Comisión de Trabajo (CT)"),
                            ("COMPENSACION_FERIADO", "Compensación por Feriado (CPF)"),
                            ("COMP_DIA_TRABAJO", "Compensación de Día por Trabajo (CDT)"),
                            ("SUSPENSION", "Suspensión Disciplinaria"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Permiso",
                    ),
                ),
                (
                    "tipo_permiso_raw",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Tipo Permiso Original (texto del archivo)",
                    ),
                ),
                (
                    "iniciales",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Iniciales del Código"
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de Fin")),
                ("detalle", models.TextField(blank=True, verbose_name="Detalle / Motivo")),
                (
                    "dias_habiles",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Días Hábiles Cubiertos"
                    ),
                ),
                (
                    "area_trabajo",
                    models.CharField(blank=True, max_length=150, verbose_name="Área de Trabajo"),
                ),
                ("cargo", models.CharField(blank=True, max_length=150, verbose_name="Cargo")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "personal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="papeletas_tareo",
                        to="personal.personal",
                        verbose_name="Personal (BD)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Papeleta",
                "verbose_name_plural": "Papeletas",
                "ordering": ["fecha_inicio", "dni"],
            },
        ),
        migrations.CreateModel(
            name="RegistroTareo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dni", models.CharField(max_length=20, verbose_name="DNI/Doc (del archivo)")),
                (
                    "nombre_archivo",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Nombre (del archivo)"
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        choices=[
                            ("STAFF", "CSRT STAFF (compensatorio — sin pago directo de HE)"),
                            ("RCO", "CSRT RCO (pago de HE en nómina S10)"),
                            ("OTRO", "Otro / Por definir"),
                        ],
                        max_length=10,
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOCAL", "Local (jornada fija en sede)"),
                            ("FORANEO", "Foráneo (régimen acumulativo 21×7)"),
                            ("LIMA", "Lima (hereda horario Local)"),
                        ],
                        max_length=10,
                        verbose_name="Condición",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Día Semana (0=Lun, 6=Dom)"
                    ),
                ),
                ("es_feriado", models.BooleanField(default=False, verbose_name="¿Es Feriado?")),
                (
                    "valor_reloj_raw",
                    models.CharField(
                        blank=True,
                        help_text="Sin procesar: número de horas, 'B', 'V', 'SS', en blanco, etc.",
                        max_length=20,
                        verbose_name="Valor Crudo del Reloj",
                    ),
                ),
                (
                    "hora_entrada_real",
                    models.TimeField(blank=True, null=True, verbose_name="Hora Entrada Real"),
                ),
                (
                    "hora_salida_real",
                    models.TimeField(blank=True, null=True, verbose_name="Hora Salida Real"),
                ),
                (
                    "horas_marcadas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Horas Marcadas (brutas del reloj)",
                    ),
                ),
                (
                    "codigo_dia",
                    models.CharField(
                        blank=True,
                        help_text="Ej: A, NOR, DL, VAC, F, DM, FL, CHE",
                        max_length=20,
                        verbose_name="Código Día (procesado)",
                    ),
                ),
                (
                    "fuente_codigo",
                    models.CharField(
                        choices=[
                            ("RELOJ", "Sistema de Asistencia"),
                            ("PAPELETA", "Papeleta de Permiso/Ausencia"),
                            ("FERIADO", "Feriado del Calendario"),
                            ("FALTA_AUTO", "Falta Automática (sin marca ni papeleta)"),
                            ("MANUAL", "Corrección Manual"),
                        ],
                        default="RELOJ",
                        max_length=15,
                        verbose_name="Fuente del Código",
                    ),
                ),
                (
                    "horas_efectivas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Horas marcadas − almuerzo",
                        max_digits=5,
                        verbose_name="Horas Efectivas",
                    ),
                ),
                (
                    "horas_normales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Horas Normales (dentro de jornada)",
                    ),
                ),
                (
                    "he_25",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="HE 25% (1ra y 2da hora extra)",
                    ),
                ),
                (
                    "he_35",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="HE 35% (3ra hora extra en adelante)",
                    ),
                ),
                (
                    "he_100",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="HE 100% (Feriado Laborado)",
                    ),
                ),
                (
                    "he_al_banco",
                    models.BooleanField(
                        default=False,
                        help_text="True = STAFF (compensatorio); False = RCO (pago nómina)",
                        verbose_name="¿HE van al Banco?",
                    ),
                ),
                (
                    "papeleta_ref",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencia Papeleta Override"
                    ),
                ),
                ("observaciones", models.TextField(blank=True, verbose_name="Observaciones")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "personal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_tareo",
                        to="personal.personal",
                        verbose_name="Personal (BD)",
                    ),
                ),
                (
                    "regimen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_tareo",
                        to="tareo.regimenturno",
                        verbose_name="Régimen Aplicado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Tareo",
                "verbose_name_plural": "Registros de Tareo",
                "ordering": ["fecha", "dni"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoBancoHoras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ACUMULACION", "Acumulación (HE generadas en tareo)"),
                            ("COMPENSACION", "Compensación (horas usadas como descanso/CHE)"),
                            ("VENCIMIENTO", "Vencimiento / Caducidad de horas"),
                            ("AJUSTE_MANUAL", "Ajuste Manual"),
                            ("LIQUIDACION", "Liquidación al cese"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                (
                    "tasa",
                    models.CharField(
                        choices=[
                            ("25", "HE 25%"),
                            ("35", "HE 35%"),
                            ("100", "HE 100% (Feriado)"),
                            ("NA", "No aplica (compensación directa)"),
                        ],
                        default="NA",
                        max_length=3,
                        verbose_name="Tasa HE",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha del Movimiento")),
                (
                    "horas",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Horas (+ acumulación / − compensación)",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=300, verbose_name="Descripción"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "banco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="tareo.bancohoras",
                        verbose_name="Banco de Horas",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que registró",
                    ),
                ),
                (
                    "papeleta_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_banco",
                        to="tareo.registropapeleta",
                        verbose_name="Papeleta Origen",
                    ),
                ),
                (
                    "registro_tareo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_banco",
                        to="tareo.registrotareo",
                        verbose_name="Registro Tareo Origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Banco de Horas",
                "verbose_name_plural": "Movimientos de Banco de Horas",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="CruceTareoRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "roster_codigo",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Código Roster Proyectado"
                    ),
                ),
                (
                    "roster_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID del Registro Roster"
                    ),
                ),
                (
                    "variacion",
                    models.CharField(
                        choices=[
                            ("COINCIDE", "Coincide — real igual al proyectado"),
                            ("TRABAJO_SIN_ROSTER", "Trabajó sin estar en Roster"),
                            ("AUSENTE_PROYECTADO", "Ausente aunque Roster marcaba trabajo"),
                            ("ROTACION_ANTICIPADA", "Rotación anticipada (llegó antes)"),
                            ("ROTACION_EXTENDIDA", "Rotación extendida (permaneció más días)"),
                            ("LICENCIA_NO_PROYECTADA", "Licencia/Permiso no proyectado en Roster"),
                            ("FALTA_NO_PROYECTADA", "Falta no proyectada"),
                            ("DL_ADELANTADO", "Día Libre tomado antes de lo proyectado"),
                            ("DL_POSTERGADO", "Día Libre postergado"),
                            ("NO_EN_TAREO", "En Roster pero sin registro de asistencia"),
                            ("NO_EN_ROSTER", "En Tareo pero sin entrada en Roster"),
                        ],
                        max_length=25,
                        verbose_name="Tipo de Variación",
                    ),
                ),
                (
                    "detalle_variacion",
                    models.TextField(blank=True, verbose_name="Detalle de la Variación"),
                ),
                (
                    "impacta_pasaje",
                    models.BooleanField(
                        default=False,
                        help_text="True si la variación altera el día libre proyectado para pasaje",
                        verbose_name="¿Impacta en Pasajes?",
                    ),
                ),
                (
                    "dias_libres_diff",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=4,
                        verbose_name="Diferencia en Días Libres (real − proyectado)",
                    ),
                ),
                ("generado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "registro_tareo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cruce_roster",
                        to="tareo.registrotareo",
                        verbose_name="Registro de Tareo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cruce Tareo–Roster",
                "verbose_name_plural": "Cruces Tareo–Roster",
                "ordering": ["-registro_tareo__fecha"],
            },
        ),
        migrations.CreateModel(
            name="TareoImportacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RELOJ", "Sistema de Asistencia / Reloj Biométrico"),
                            ("PAPELETAS", "Papeletas de Permisos y Ausencias"),
                            ("SUNAT", "Reporte SUNAT / PLAME"),
                            ("S10", "Reporte S10 (Nómina)"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Fuente",
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Inicio del Período de Tareo")),
                ("periodo_fin", models.DateField(verbose_name="Fin del Período de Tareo")),
                (
                    "archivo_nombre",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre del Archivo Original"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tareo/importaciones/%Y/%m/",
                        verbose_name="Archivo Cargado",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Procesamiento"),
                            ("PROCESANDO", "En Proceso"),
                            ("COMPLETADO", "Completado sin Errores"),
                            ("COMPLETADO_CON_ERRORES", "Completado con Errores"),
                            ("FALLIDO", "Fallido"),
                        ],
                        default="PENDIENTE",
                        max_length=25,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "total_registros",
                    models.PositiveIntegerField(default=0, verbose_name="Total de Registros"),
                ),
                (
                    "registros_ok",
                    models.PositiveIntegerField(default=0, verbose_name="Registros OK"),
                ),
                (
                    "registros_error",
                    models.PositiveIntegerField(default=0, verbose_name="Registros con Error"),
                ),
                (
                    "registros_sin_match",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sin Match con Personal (DNI no en BD)"
                    ),
                ),
                (
                    "errores",
                    models.JSONField(
                        default=list,
                        help_text="Lista de {'fila': N, 'dni': '...', 'mensaje': '...'}",
                        verbose_name="Errores",
                    ),
                ),
                ("advertencias", models.JSONField(default=list, verbose_name="Advertencias")),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Hoja origen, ciclo detectado, sistema, etc.",
                        verbose_name="Metadatos",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("procesado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareo_importaciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Importado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Importación de Tareo",
                "verbose_name_plural": "Importaciones de Tareo",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AddField(
            model_name="registrotareo",
            name="importacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros",
                to="tareo.tareoimportacion",
                verbose_name="Importación Origen",
            ),
        ),
        migrations.CreateModel(
            name="RegistroSUNAT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo_doc",
                    models.CharField(blank=True, max_length=20, verbose_name="Tipo de Documento"),
                ),
                ("nro_doc", models.CharField(max_length=20, verbose_name="Nro. Documento")),
                (
                    "apellidos_nombres",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Apellidos y Nombres"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(blank=True, max_length=7, verbose_name="Período (MM/AAAA)"),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Ingreso"),
                ),
                (
                    "fecha_cese",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Cese"),
                ),
                (
                    "remuneracion_basica",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Remuneración Básica (S/)",
                    ),
                ),
                (
                    "dias_laborados",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Días Laborados"
                    ),
                ),
                (
                    "horas_extras_reportadas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Horas Extras Reportadas a SUNAT",
                    ),
                ),
                (
                    "essalud",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="EsSalud (S/)",
                    ),
                ),
                (
                    "aporte_pension",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Aporte Pensión (S/)",
                    ),
                ),
                (
                    "tipo_trabajador_sunat",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Tipo Trabajador SUNAT"
                    ),
                ),
                (
                    "datos_extra",
                    models.JSONField(default=dict, verbose_name="Campos Adicionales (JSON)"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "personal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_sunat",
                        to="personal.personal",
                        verbose_name="Personal (BD)",
                    ),
                ),
                (
                    "importacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_sunat",
                        to="tareo.tareoimportacion",
                        verbose_name="Importación Origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro SUNAT",
                "verbose_name_plural": "Registros SUNAT",
                "ordering": ["periodo", "nro_doc"],
            },
        ),
        migrations.CreateModel(
            name="RegistroS10",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codigo_s10",
                    models.CharField(blank=True, max_length=20, verbose_name="Código S10"),
                ),
                (
                    "tipo_doc",
                    models.CharField(blank=True, max_length=20, verbose_name="Tipo de Documento"),
                ),
                ("nro_doc", models.CharField(max_length=20, verbose_name="Nro. Documento")),
                (
                    "apellidos_nombres",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Apellidos y Nombres"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(blank=True, max_length=100, verbose_name="Categoría"),
                ),
                (
                    "ocupacion",
                    models.CharField(blank=True, max_length=150, verbose_name="Ocupación / Cargo"),
                ),
                (
                    "condicion",
                    models.CharField(blank=True, max_length=20, verbose_name="Condición"),
                ),
                (
                    "periodo",
                    models.CharField(blank=True, max_length=7, verbose_name="Período (MM/AAAA)"),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Ingreso"),
                ),
                (
                    "fecha_cese",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de Cese"),
                ),
                (
                    "en_tareo",
                    models.BooleanField(default=True, verbose_name="¿En Tareo? (flag S10)"),
                ),
                (
                    "adelanto_condicion_trabajo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Adelanto Condición de Trabajo (S/)",
                    ),
                ),
                (
                    "horas_extra_25",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="HE 25% (h) en S10",
                    ),
                ),
                (
                    "horas_extra_35",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="HE 35% (h) en S10",
                    ),
                ),
                (
                    "horas_extra_100",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="HE 100% (h) en S10",
                    ),
                ),
                (
                    "partida_control",
                    models.CharField(blank=True, max_length=100, verbose_name="Partida de Control"),
                ),
                (
                    "codigo_proyecto",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Código Proyecto Destino"
                    ),
                ),
                (
                    "regimen_pension",
                    models.CharField(blank=True, max_length=50, verbose_name="Régimen Pensión"),
                ),
                (
                    "datos_extra",
                    models.JSONField(default=dict, verbose_name="Campos Adicionales (JSON)"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "personal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_s10",
                        to="personal.personal",
                        verbose_name="Personal (BD)",
                    ),
                ),
                (
                    "importacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_s10",
                        to="tareo.tareoimportacion",
                        verbose_name="Importación Origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro S10",
                "verbose_name_plural": "Registros S10",
                "ordering": ["periodo", "nro_doc"],
            },
        ),
        migrations.AddField(
            model_name="registropapeleta",
            name="importacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papeletas",
                to="tareo.tareoimportacion",
                verbose_name="Importación Origen",
            ),
        ),
        migrations.CreateModel(
            name="TipoHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: 'Foráneo L-S', 'Local Domingo'",
                        max_length=60,
                        verbose_name="Nombre del Horario",
                    ),
                ),
                (
                    "tipo_dia",
                    models.CharField(
                        choices=[
                            ("LUNES_VIERNES", "Lunes a Viernes"),
                            ("SABADO", "Sábado"),
                            ("DOMINGO", "Domingo"),
                            ("LUNES_SABADO", "Lunes a Sábado"),
                            ("TODOS", "Todos los días del ciclo"),
                            ("TURNO_A", "Turno A (rotativo)"),
                            ("TURNO_B", "Turno B (rotativo)"),
                            ("TURNO_C", "Turno C (rotativo)"),
                            ("ESPECIAL", "Especial / Personalizado"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Día",
                    ),
                ),
                ("hora_entrada", models.TimeField(verbose_name="Hora de Entrada")),
                ("hora_salida", models.TimeField(verbose_name="Hora de Salida")),
                (
                    "salida_dia_siguiente",
                    models.BooleanField(
                        default=False,
                        help_text="Activar para turnos nocturnos que cruzan medianoche",
                        verbose_name="¿Salida al día siguiente?",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "regimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="tareo.regimenturno",
                        verbose_name="Régimen de Turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Horario",
                "verbose_name_plural": "Tipos de Horario",
                "ordering": ["regimen", "tipo_dia"],
            },
        ),
        migrations.AddIndex(
            model_name="bancohoras",
            index=models.Index(
                fields=["personal", "periodo_anio", "periodo_mes"],
                name="tareo_banco_persona_2f8f2a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bancohoras",
            unique_together={("personal", "periodo_anio", "periodo_mes")},
        ),
        migrations.AddIndex(
            model_name="movimientobancohoras",
            index=models.Index(fields=["banco", "fecha"], name="tareo_movim_banco_i_95dd15_idx"),
        ),
        migrations.AddIndex(
            model_name="crucetareoroster",
            index=models.Index(fields=["variacion"], name="tareo_cruce_variaci_8d2118_idx"),
        ),
        migrations.AddIndex(
            model_name="crucetareoroster",
            index=models.Index(fields=["impacta_pasaje"], name="tareo_cruce_impacta_5bd1df_idx"),
        ),
        migrations.AddIndex(
            model_name="registrotareo",
            index=models.Index(fields=["dni", "fecha"], name="tareo_regis_dni_d91699_idx"),
        ),
        migrations.AddIndex(
            model_name="registrotareo",
            index=models.Index(
                fields=["importacion", "grupo"], name="tareo_regis_importa_0c1f16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrotareo",
            index=models.Index(fields=["personal", "fecha"], name="tareo_regis_persona_97aaa4_idx"),
        ),
        migrations.AddIndex(
            model_name="registrotareo",
            index=models.Index(fields=["fecha", "grupo"], name="tareo_regis_fecha_242c69_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="registrotareo",
            unique_together={("importacion", "dni", "fecha")},
        ),
        migrations.AddIndex(
            model_name="registrosunat",
            index=models.Index(
                fields=["nro_doc", "periodo"], name="tareo_regis_nro_doc_4c0a28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registros10",
            index=models.Index(
                fields=["nro_doc", "periodo"], name="tareo_regis_nro_doc_132145_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registros10",
            index=models.Index(fields=["codigo_s10"], name="tareo_regis_codigo__c8ce98_idx"),
        ),
        migrations.AddIndex(
            model_name="registropapeleta",
            index=models.Index(
                fields=["dni", "fecha_inicio", "fecha_fin"], name="tareo_regis_dni_67ac66_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tipohorario",
            unique_together={("regimen", "tipo_dia")},
        ),
    ]
