# Generated by Django 5.1.15 on 2026-02-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0002_configuracionsistema_conceptomapeos10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='email_asunto_semanal',
            field=models.CharField(default='Tu resumen de asistencia semanal — {empresa}', help_text='Usa {empresa}, {semana}, {empleado} como variables', max_length=200, verbose_name='Asunto Email Semanal'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='email_desde',
            field=models.EmailField(blank=True, help_text='Ej: tareo@empresa.com', max_length=254, verbose_name='Email Remitente'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='email_dia_envio',
            field=models.PositiveSmallIntegerField(default=0, help_text='Día de la semana para enviar el resumen semanal', verbose_name='Día de Envío (0=Lun … 6=Dom)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='regularizacion_activa',
            field=models.BooleanField(default=True, help_text='Si está activo, los descuentos (faltas, LSG) entre el día (corte+1) y fin de mes se difieren al siguiente mes como regularización.', verbose_name='Activar Regularización de Fin de Mes'),
        ),
    ]
