# Generated by Django 5.1.15 on 2026-03-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0003_alter_configuracionsistema_email_asunto_semanal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='ia_endpoint',
            field=models.CharField(blank=True, default='http://localhost:11434', help_text='URL del servidor IA. Para Ollama local: http://localhost:11434', max_length=200, verbose_name='Endpoint IA'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='ia_modelo',
            field=models.CharField(blank=True, default='llama3.2', help_text='Ej: llama3.2, mistral, claude-sonnet-4-6, gpt-4o-mini', max_length=100, verbose_name='Modelo IA'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='ia_provider',
            field=models.CharField(choices=[('ANTHROPIC', 'Anthropic (Claude API)'), ('OLLAMA', 'Ollama (Local — Llama / Mistral)'), ('OPENAI', 'OpenAI (GPT)'), ('NINGUNO', 'Sin IA')], default='NINGUNO', help_text='Motor de IA para detección de columnas y validaciones', max_length=20, verbose_name='Proveedor de IA'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='Solo para proveedor OpenAI', max_length=200, verbose_name='OpenAI API Key'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='anthropic_api_key',
            field=models.CharField(blank=True, help_text='Solo para proveedor Anthropic. Dejar vacío para mantener la clave actual', max_length=200, verbose_name='Anthropic API Key'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ia_mapeo_activo',
            field=models.BooleanField(default=False, help_text='Usa IA para detectar columnas en archivos desconocidos automáticamente', verbose_name='Activar Mapeo IA de Columnas'),
        ),
    ]
