# Generated by Django 5.1.15 on 2026-03-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0004_add_ia_provider_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='anthropic_api_key',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='openai_api_key',
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ia_endpoint',
            field=models.CharField(blank=True, default='http://localhost:11434', help_text='URL del servidor Ollama. Por defecto: http://localhost:11434', max_length=200, verbose_name='Endpoint Ollama'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ia_mapeo_activo',
            field=models.BooleanField(default=False, help_text='Detecta automáticamente columnas en archivos de importación desconocidos', verbose_name='Activar Mapeo IA de Columnas'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ia_modelo',
            field=models.CharField(blank=True, default='llama3.2', help_text='Nombre del modelo instalado. Ej: llama3.2, mistral, qwen2.5', max_length=100, verbose_name='Modelo Ollama'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ia_provider',
            field=models.CharField(choices=[('OLLAMA', 'Ollama (Local — Llama / Mistral)'), ('NINGUNO', 'Sin IA')], default='NINGUNO', help_text='Motor de IA local (Ollama) para detección automática de columnas', max_length=20, verbose_name='Proveedor de IA'),
        ),
    ]
