# Generated by Django 5.1.15 on 2026-03-01 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_personal_grupo_tareo_condicion_codigos'),
        ('tareo', '0005_remove_cloud_api_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PapeletaCompensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado Trabajado'), ('DSO', 'Descanso Semanal Trabajado')], max_length=10, verbose_name='Tipo')),
                ('fecha_trabajada', models.DateField(help_text='Día feriado o DSO en que el trabajador laboró', verbose_name='Fecha Trabajada')),
                ('fecha_compensacion', models.DateField(blank=True, help_text='Día libre que se otorga como compensación', null=True, verbose_name='Fecha Compensación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EJECUTADA', 'Ejecutada — compensación tomada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papeletas_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeletas_compensacion', to='personal.personal', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Papeleta de Compensación',
                'verbose_name_plural': 'Papeletas de Compensación',
                'ordering': ['-fecha_trabajada'],
                'unique_together': {('personal', 'fecha_trabajada')},
            },
        ),
    ]
