# Generated by Django 5.1.15 on 2026-03-01 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_personal_grupo_tareo_condicion_codigos'),
        ('tareo', '0006_add_papeleta_compensacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='he_requiere_solicitud',
            field=models.BooleanField(default=False, help_text='Si activo, las HE solo se registran si hay una SolicitudHE aprobada. Sin solicitud aprobada el exceso se ignora (no va a banco ni nómina).', verbose_name='Requiere solicitud previa para HE'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='he_tipo_default',
            field=models.CharField(choices=[('PAGABLE', 'Pagable (se liquida en planilla: 25%/35%/100%)'), ('COMPENSABLE', 'Compensable (va al Banco de Horas; se paga en liquidación si no se compensa)')], default='PAGABLE', help_text='Tipo aplicado cuando la solicitud no especifica tipo. STAFF por naturaleza es compensable; RCO es pagable.', max_length=20, verbose_name='Tipo de HE por defecto'),
        ),
        migrations.CreateModel(
            name='SolicitudHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Día en que se realizarán/realizaron las HE', verbose_name='Fecha')),
                ('horas_estimadas', models.DecimalField(decimal_places=2, default=0, help_text='Estimación de HE a trabajar ese día', max_digits=4, verbose_name='Horas Estimadas')),
                ('tipo', models.CharField(choices=[('PAGABLE', 'Pagable (planilla)'), ('COMPENSABLE', 'Compensable (banco de horas)')], default='PAGABLE', max_length=20, verbose_name='Tipo de HE')),
                ('motivo', models.TextField(verbose_name='Motivo / Justificación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha Aprobación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del aprobador')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_he_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_he', to='personal.personal', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Solicitud de Horas Extra',
                'verbose_name_plural': 'Solicitudes de Horas Extra',
                'ordering': ['-fecha', '-creado_en'],
                'unique_together': {('personal', 'fecha')},
            },
        ),
    ]
