# Generated by Django 5.1.15 on 2026-03-01 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_personal_grupo_tareo_condicion_codigos'),
        ('tareo', '0007_add_solicitud_he_and_config_he'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificacionNoMarcaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha justificada')),
                ('tipo', models.CharField(choices=[('TARDANZA', 'Tardanza justificada'), ('FALTA_JUSTIFICADA', 'Falta justificada'), ('TRABAJO_REMOTO', 'Trabajo remoto / Teletrabajo'), ('SALIDA_TEMPRANA', 'Salida temprana autorizada'), ('COMISION', 'Comisión de servicios / Viaje'), ('CAPACITACION', 'Capacitación externa'), ('MEDICO', 'Cita médica / EPS'), ('OTRO', 'Otro')], max_length=25, verbose_name='Tipo')),
                ('motivo', models.TextField(verbose_name='Motivo / Detalle')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_revision', models.DateField(blank=True, null=True, verbose_name='Fecha revisión')),
                ('comentario_revisor', models.TextField(blank=True, verbose_name='Comentario del revisor')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones_marcaje', to='personal.personal', verbose_name='Trabajador')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Justificación de No-Marcaje',
                'verbose_name_plural': 'Justificaciones de No-Marcaje',
                'ordering': ['-fecha', '-creado_en'],
                'unique_together': {('personal', 'fecha')},
            },
        ),
    ]
