# Generated by Django 5.1.15 on 2026-03-01 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_personal_grupo_tareo_condicion_codigos'),
        ('tareo', '0008_add_justificacion_no_marcaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registropapeleta',
            options={'ordering': ['-fecha_inicio', 'dni'], 'verbose_name': 'Papeleta', 'verbose_name_plural': 'Papeletas'},
        ),
        migrations.AddField(
            model_name='registropapeleta',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registropapeleta',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papeletas_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='registropapeleta',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papeletas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='registropapeleta',
            name='estado',
            field=models.CharField(choices=[('APROBADA', 'Aprobada'), ('PENDIENTE', 'Pendiente de aprobación'), ('RECHAZADA', 'Rechazada'), ('EJECUTADA', 'Ejecutada'), ('ANULADA', 'Anulada')], default='APROBADA', help_text='Importadas = Aprobada por defecto; manuales = Pendiente', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='registropapeleta',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Aprobación'),
        ),
        migrations.AddField(
            model_name='registropapeleta',
            name='fecha_referencia',
            field=models.DateField(blank=True, help_text='Para compensaciones: fecha del feriado/DSO trabajado que origina esta papeleta', null=True, verbose_name='Fecha Referencia'),
        ),
        migrations.AddField(
            model_name='registropapeleta',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='registropapeleta',
            name='origen',
            field=models.CharField(choices=[('IMPORTACION', 'Importación (Synkro/Excel)'), ('SISTEMA', 'Creada por Administrador'), ('PORTAL', 'Solicitada por Trabajador')], default='IMPORTACION', max_length=15, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='papeletacompensacion',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papeletas_comp_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AlterField(
            model_name='registropapeleta',
            name='importacion',
            field=models.ForeignKey(blank=True, help_text='Solo para papeletas importadas; null si fue creada en el sistema', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papeletas', to='tareo.tareoimportacion', verbose_name='Importación Origen'),
        ),
        migrations.AlterField(
            model_name='registropapeleta',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papeletas_tareo', to='personal.personal', verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='registropapeleta',
            name='tipo_permiso',
            field=models.CharField(choices=[('COMPENSACION_HE', 'Compensación por Horario Extendido (CHE)'), ('BAJADAS', 'Bajadas / Día Libre (DL)'), ('BAJADAS_ACUMULADAS', 'Bajadas Acumuladas (DLA)'), ('VACACIONES', 'Vacaciones (VAC)'), ('DESCANSO_MEDICO', 'Descanso Médico (DM)'), ('LICENCIA_CON_GOCE', 'Licencia con Goce (LCG)'), ('LICENCIA_SIN_GOCE', 'Licencia sin Goce (LSG)'), ('LICENCIA_FALLECIMIENTO', 'Licencia por Fallecimiento (LF)'), ('LICENCIA_PATERNIDAD', 'Licencia por Paternidad (LP)'), ('LICENCIA_MATERNIDAD', 'Licencia por Maternidad (LM)'), ('COMISION_TRABAJO', 'Comisión de Trabajo (CT)'), ('COMPENSACION_FERIADO', 'Compensación por Feriado (CPF)'), ('COMP_DIA_TRABAJO', 'Compensación de Día por Trabajo (CDT)'), ('SUSPENSION', 'Suspensión Disciplinaria'), ('CAPACITACION', 'Capacitación (CAP)'), ('TRABAJO_REMOTO', 'Trabajo Remoto (TR)'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo de Permiso'),
        ),
        migrations.AddIndex(
            model_name='registropapeleta',
            index=models.Index(fields=['personal', 'estado', 'tipo_permiso'], name='tareo_regis_persona_3953e6_idx'),
        ),
    ]
