# Generated by Django 5.1.15 on 2026-03-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0009_unificar_papeletas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='export_formato',
            field=models.CharField(choices=[('XLSX', 'Excel (.xlsx)'), ('CSV', 'CSV'), ('PDF', 'PDF')], default='XLSX', max_length=10, verbose_name='Formato de exportación por defecto'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='export_incluir_banco_horas',
            field=models.BooleanField(default=True, verbose_name='Incluir Banco de Horas'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='export_incluir_faltas',
            field=models.BooleanField(default=True, verbose_name='Incluir Faltas/Descuentos'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='export_incluir_sueldo',
            field=models.BooleanField(default=False, verbose_name='Incluir Sueldo Base en exportación'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='export_separar_staff_rco',
            field=models.BooleanField(default=True, verbose_name='Separar STAFF / RCO en archivos distintos'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mod_capacitaciones',
            field=models.BooleanField(default=False, verbose_name='Capacitaciones / LMS'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mod_documentos',
            field=models.BooleanField(default=True, verbose_name='Legajo Digital y Constancias'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mod_encuestas',
            field=models.BooleanField(default=False, verbose_name='Encuestas y Clima Laboral'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mod_evaluaciones',
            field=models.BooleanField(default=False, verbose_name='Evaluaciones de Desempeño'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mod_prestamos',
            field=models.BooleanField(default=True, verbose_name='Préstamos y Adelantos'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mod_reclutamiento',
            field=models.BooleanField(default=False, verbose_name='Reclutamiento y Selección'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mod_viaticos',
            field=models.BooleanField(default=False, verbose_name='Viáticos y CDT'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='modo_sistema',
            field=models.CharField(choices=[('ASISTENCIA', 'Solo Asistencia'), ('ASISTENCIA_NOMINA', 'Asistencia + Nómina'), ('ERP_COMPLETO', 'ERP Completo')], default='ASISTENCIA', help_text='Define el alcance: Solo tareo/reloj, con nómina integrada, o ERP completo', max_length=20, verbose_name='Modo del Sistema'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='programa_nomina',
            field=models.CharField(choices=[('NINGUNO', 'Sin programa externo'), ('S10', 'S10 — Costos y Presupuestos'), ('SAP', 'SAP'), ('EXCEL', 'Excel manual'), ('OTRO', 'Otro sistema')], default='S10', help_text='Sistema donde se procesa la nómina. Determina formato de exportación.', max_length=20, verbose_name='Programa de Nómina Destino'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='programa_nomina_nombre',
            field=models.CharField(blank=True, default='', help_text="Solo si eligió 'Otro'. Ej: Exactus, Contasis, Starsoft", max_length=100, verbose_name='Nombre del Programa (si es Otro)'),
        ),
    ]
