# Generated by Django 5.1.15 on 2026-03-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0010_add_modo_sistema_modulos_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='mod_salarios',
            field=models.BooleanField(default=False, verbose_name='Estructura Salarial'),
        ),
    ]
