# Generated by Django 5.1.15 on 2026-03-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0011_add_mod_salarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='empresa_direccion',
            field=models.CharField(blank=True, default='', help_text='Dirección completa de la empresa. Aparece en membretes y constancias.', max_length=300, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='empresa_email',
            field=models.EmailField(blank=True, default='', help_text='Email de contacto que aparece en documentos', max_length=254, verbose_name='Email corporativo'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='empresa_telefono',
            field=models.CharField(blank=True, default='', help_text='Ej: (01) 234-5678 / Nextel 123*456', max_length=50, verbose_name='Teléfono / Anexo'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='empresa_web',
            field=models.CharField(blank=True, default='', help_text='Ej: www.empresa.com.pe', max_length=200, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='firma_cargo',
            field=models.CharField(blank=True, default='', help_text='Ej: Jefe de Recursos Humanos', max_length=200, verbose_name='Cargo del firmante'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='firma_imagen',
            field=models.ImageField(blank=True, help_text='PNG con fondo transparente. Recomendado: 200×80px.', null=True, upload_to='empresa/firmas/', verbose_name='Imagen de firma'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='firma_nombre',
            field=models.CharField(blank=True, default='', help_text='Ej: Juan Pérez García', max_length=200, verbose_name='Nombre del firmante'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG o JPG con fondo transparente. Recomendado: 300×100px.', null=True, upload_to='empresa/logo/', verbose_name='Logo empresa'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='membrete_color',
            field=models.CharField(default='#0f766e', help_text='Color principal del membrete en formato HEX. Ej: #0f766e', max_length=7, verbose_name='Color membrete'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='membrete_mostrar',
            field=models.BooleanField(default=True, help_text='Si está activo, agrega el membrete automáticamente a todas las constancias generadas.', verbose_name='Usar membrete en documentos'),
        ),
    ]
