# Generated by Django 5.1 — Harmoni Fase ZKTeco

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0012_add_identidad_visual_membrete'),
        ('personal', '__first__'),
    ]

    operations = [
        # ── RelojBiometrico ──────────────────────────────────────────────
        migrations.CreateModel(
            name='RelojBiometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del dispositivo',
                                            help_text='Ej: Reloj Planta Principal, Control Acceso Lima')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación física',
                                               help_text='Ej: Planta Arequipa — Control de acceso principal')),
                ('descripcion', models.TextField(blank=True, verbose_name='Notas / descripción')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Dirección IP',
                                                    help_text='IP del dispositivo en la red local. Ej: 192.168.1.100')),
                ('puerto', models.PositiveIntegerField(default=4370, verbose_name='Puerto TCP/UDP',
                                                       help_text='Puerto ZK. Estándar: 4370.')),
                ('timeout', models.PositiveSmallIntegerField(default=10, verbose_name='Timeout (segundos)')),
                ('protocolo', models.CharField(
                    choices=[('TCP', 'TCP — Recomendado (dispositivos ZKTeco 2015+)'),
                             ('UDP', 'UDP — Dispositivos antiguos / firmware legacy')],
                    default='TCP', max_length=5, verbose_name='Protocolo')),
                ('campo_id_empleado', models.CharField(
                    choices=[('USER_ID', 'User ID del dispositivo (igual al DNI del empleado)'),
                             ('CARD', 'Número de tarjeta / badge registrado')],
                    default='USER_ID', max_length=20, verbose_name='Campo para identificar empleado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('estado_conexion', models.CharField(
                    choices=[('SIN_VERIFICAR', 'Sin verificar'), ('CONECTADO', '✓ Conectado'),
                             ('DESCONECTADO', '✗ Desconectado'), ('ERROR', '⚠ Error de comunicación')],
                    default='SIN_VERIFICAR', max_length=20, verbose_name='Estado de conexión')),
                ('numero_serie', models.CharField(blank=True, max_length=50, verbose_name='Número de serie')),
                ('modelo_dispositivo', models.CharField(blank=True, max_length=100, verbose_name='Modelo / Firmware')),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True,
                                                                verbose_name='Última sincronización')),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True,
                                                              verbose_name='Última verificación de conexión')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reloj Biométrico',
                'verbose_name_plural': 'Relojes Biométricos',
                'ordering': ['nombre'],
            },
        ),

        # ── MarcacionBiometrica ──────────────────────────────────────────
        migrations.CreateModel(
            name='MarcacionBiometrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reloj', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='marcaciones',
                    to='tareo.relojbiometrico',
                    verbose_name='Reloj')),
                ('user_id_dispositivo', models.CharField(max_length=20, verbose_name='ID en dispositivo',
                                                          help_text='Valor del user_id registrado en el ZKTeco')),
                ('personal', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='marcaciones_biometricas',
                    to='personal.personal',
                    verbose_name='Personal')),
                ('timestamp', models.DateTimeField(verbose_name='Fecha / Hora de marcación')),
                ('tipo_marcacion', models.CharField(
                    choices=[('ENTRADA', 'Entrada / Check-in'), ('SALIDA', 'Salida / Check-out'),
                             ('DESCANSO_SALIDA', 'Salida de descanso'),
                             ('DESCANSO_REGRESO', 'Regreso de descanso'),
                             ('HE_SALIDA', 'Salida por horas extra'), ('OTRO', 'Otro / Desconocido')],
                    default='ENTRADA', max_length=20, verbose_name='Tipo de marcación')),
                ('punch_raw', models.SmallIntegerField(default=0, verbose_name='Código punch (raw)',
                                                       help_text='0=entrada, 1=salida, 4=HE salida…')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado')),
                ('importacion', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='marcaciones_biometricas',
                    to='tareo.TareoImportacion',
                    verbose_name='Importación de tareo generada')),
            ],
            options={
                'verbose_name': 'Marcación Biométrica',
                'verbose_name_plural': 'Marcaciones Biométricas',
                'ordering': ['timestamp'],
            },
        ),

        # ── Unique together + indexes ────────────────────────────────────
        migrations.AlterUniqueTogether(
            name='marcacionbiometrica',
            unique_together={('reloj', 'user_id_dispositivo', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='marcacionbiometrica',
            index=models.Index(fields=['reloj', 'timestamp'], name='tareo_marc_reloj_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='marcacionbiometrica',
            index=models.Index(fields=['personal', 'timestamp'], name='tareo_marc_pers_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='marcacionbiometrica',
            index=models.Index(fields=['procesado', 'timestamp'], name='tareo_marc_proc_ts_idx'),
        ),
    ]
