# Generated by Django 5.1.15 on 2026-03-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0013_add_relojes_biometricos'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marcacionbiometrica',
            new_name='tareo_marca_reloj_i_f0ac05_idx',
            old_name='tareo_marc_reloj_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='marcacionbiometrica',
            new_name='tareo_marca_persona_150029_idx',
            old_name='tareo_marc_pers_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='marcacionbiometrica',
            new_name='tareo_marca_procesa_2f4bfe_idx',
            old_name='tareo_marc_proc_ts_idx',
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='zapsign_activo',
            field=models.BooleanField(default=False, help_text='Habilitar modulo de firma digital con ZapSign', verbose_name='Firma Digital Activa'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='zapsign_api_key',
            field=models.CharField(blank=True, help_text='Token API de ZapSign para firma digital. Obtener en app.zapsign.com.br/settings/tokens', max_length=200, verbose_name='ZapSign API Key'),
        ),
        migrations.AlterField(
            model_name='marcacionbiometrica',
            name='procesado',
            field=models.BooleanField(default=False, help_text='True cuando ya fue incluido en una importación de tareo', verbose_name='Procesado'),
        ),
        migrations.AlterField(
            model_name='marcacionbiometrica',
            name='punch_raw',
            field=models.SmallIntegerField(default=0, help_text='Valor original del ZKTeco: 0=entrada, 1=salida, 4=HE salida…', verbose_name='Código punch (raw)'),
        ),
        migrations.AlterField(
            model_name='relojbiometrico',
            name='activo',
            field=models.BooleanField(default=True, help_text='Los relojes inactivos no se sincronizan en procesos automáticos', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='relojbiometrico',
            name='campo_id_empleado',
            field=models.CharField(choices=[('USER_ID', 'User ID del dispositivo (igual al DNI del empleado)'), ('CARD', 'Número de tarjeta / badge registrado')], default='USER_ID', help_text='Cómo se almacena el DNI en el dispositivo', max_length=20, verbose_name='Campo para identificar empleado'),
        ),
        migrations.AlterField(
            model_name='relojbiometrico',
            name='puerto',
            field=models.PositiveIntegerField(default=4370, help_text='Puerto ZK. Estándar: 4370. No cambiar sin acceso al firmware.', verbose_name='Puerto TCP/UDP'),
        ),
        migrations.AlterField(
            model_name='relojbiometrico',
            name='timeout',
            field=models.PositiveSmallIntegerField(default=10, help_text='Tiempo máximo de espera para conectar al dispositivo', verbose_name='Timeout (segundos)'),
        ),
        migrations.AlterField(
            model_name='tareoimportacion',
            name='tipo',
            field=models.CharField(choices=[('RELOJ', 'Sistema de Asistencia / Reloj Biométrico'), ('ZK', 'ZKTeco — Sincronización Directa'), ('PAPELETAS', 'Papeletas de Permisos y Ausencias'), ('SUNAT', 'Reporte SUNAT / PLAME'), ('S10', 'Reporte S10 (Nómina)')], max_length=20, verbose_name='Tipo de Fuente'),
        ),
    ]
