# Generated by Django 5.1.15 on 2026-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0014_add_zapsign_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='fecha_apertura',
            field=models.DateField(blank=True, help_text='Fecha desde la que el cliente usa Harmoni. El importador advertirá si se intentan cargar datos anteriores a esta fecha. Dejar en blanco para no validar.', null=True, verbose_name='Fecha de Apertura del Sistema'),
        ),
    ]
