# Generated by Django 5.1.15 on 2026-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0015_add_fecha_apertura_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='mod_roster',
            field=models.BooleanField(default=False, help_text='Activa el panel matricial de roster para planificar bajadas y pasajes. Solo es necesario si tienes personal foráneo con régimen de turnos (14x7, 21x7, etc.). Empresas con personal Lima/Local pueden desactivarlo — los días libres se gestionan directamente como permisos/vacaciones.', verbose_name='Roster (Control Proyectado)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='roster_aplica_a',
            field=models.CharField(choices=[('FORANEOS', 'Solo Personal Foráneo'), ('TODOS', 'Todos los trabajadores')], default='FORANEOS', help_text="Define qué personal aparece en el panel de roster. 'Solo Foráneo' es lo habitual (régimen acumulativo, pasajes aéreos). 'Todos' si el turno rotativo aplica también a personal Lima/Local.", max_length=10, verbose_name='Roster aplica a'),
        ),
    ]
