# Generated by Django 5.1.15 on 2026-03-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0019_ia_modelo_default_gemini25'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ia_modelo',
            field=models.CharField(blank=True, default='gemini-2.5-flash', help_text='Gemini: gemini-2.5-flash | gemini-2.5-pro | DeepSeek: deepseek-chat | OpenAI: gpt-4o-mini | Ollama: llama3.2', max_length=100, verbose_name='Modelo'),
        ),
    ]
