# Generated by Django 5.1.15 on 2026-03-09 03:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0022_whatsapp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='rmv_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1025.00'), help_text='Remuneración Mínima Vital vigente. Desde abr-2022: S/ 1,025. Se usa para asignación familiar (10% RMV = S/ 102.50) y otros cálculos.', max_digits=8, verbose_name='RMV / Sueldo Mínimo (S/)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='uit_anno',
            field=models.PositiveSmallIntegerField(default=2026, help_text='Año de vigencia del valor UIT configurado.', verbose_name='Año UIT'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='uit_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('5500.00'), help_text='Unidad Impositiva Tributaria vigente. 2026: S/ 5,500 (DS 233-2025-EF). Impacta IR 5ta categoría, gratificaciones y otros cálculos.', max_digits=8, verbose_name='UIT (S/)'),
        ),
    ]
