# Generated by Django 5.1.15 on 2026-03-28 13:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0028_add_jornada_domingo_horas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioCodigoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_anterior', models.CharField(max_length=20)),
                ('codigo_nuevo', models.CharField(max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('sustento', models.FileField(blank=True, null=True, upload_to='asistencia/sustentos/%Y/%m/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cambio de Código',
                'verbose_name_plural': 'Cambios de Código',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.RemoveIndex(
            model_name='registropapeleta',
            name='papeleta_fechas_idx',
        ),
        migrations.RemoveIndex(
            model_name='registropapeleta',
            name='papeleta_estado_idx',
        ),
        migrations.RemoveIndex(
            model_name='registrotareo',
            name='tareo_codigo_dia_idx',
        ),
        migrations.RemoveIndex(
            model_name='tareoimportacion',
            name='importacion_estado_idx',
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='jornada_local_horas',
            field=models.DecimalField(decimal_places=1, default=Decimal('8.5'), help_text='Ej: 8.5 para personal LOCAL 7:30–17:00 (incluye 30 min almuerzo pagado)', max_digits=4, verbose_name='Jornada Local Lun–Vie (h/día)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='openclaw_gateway_token',
            field=models.CharField(blank=True, default='', help_text='Token de autenticación para OpenClaw (si aplica).', max_length=200, verbose_name='OpenClaw Gateway Token'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='openclaw_gateway_url',
            field=models.CharField(blank=True, default='http://localhost:19000', help_text='URL del gateway OpenClaw para envío de WhatsApp.', max_length=200, verbose_name='OpenClaw Gateway URL'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='rmv_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1130.00'), help_text='Remuneración Mínima Vital vigente. Desde ene-2025: S/ 1,130 (DS 006-2024-TR). Se usa para asignación familiar (10% RMV = S/ 113.00) y otros cálculos.', max_digits=8, verbose_name='RMV / Sueldo Mínimo (S/)'),
        ),
        migrations.AlterField(
            model_name='registropapeleta',
            name='tipo_permiso',
            field=models.CharField(choices=[('COMPENSACION_HE', 'Compensación por Horario Extendido (CHE)'), ('BAJADAS', 'Bajadas / Día Libre (DL)'), ('BAJADAS_ACUMULADAS', 'Bajadas Acumuladas (DLA)'), ('VACACIONES', 'Vacaciones (VAC)'), ('DESCANSO_MEDICO', 'Descanso Médico (DM)'), ('LICENCIA_CON_GOCE', 'Licencia con Goce (LCG)'), ('LICENCIA_SIN_GOCE', 'Licencia sin Goce (LSG)'), ('LICENCIA_FALLECIMIENTO', 'Licencia por Fallecimiento (LF)'), ('LICENCIA_PATERNIDAD', 'Licencia por Paternidad (LP)'), ('LICENCIA_MATERNIDAD', 'Licencia por Maternidad (LM)'), ('COMISION_TRABAJO', 'Comisión de Trabajo (CT)'), ('COMPENSACION_FERIADO', 'Compensación por Feriado (CPF)'), ('COMP_DIA_TRABAJO', 'Compensación de Día por Trabajo (CDT)'), ('SUSPENSION', 'Suspensión Disciplinaria'), ('SUSPENSION_ACTO_INSEGURO', 'Suspensión por Acto Inseguro (SAI)'), ('CAPACITACION', 'Capacitación (CAP)'), ('TRABAJO_REMOTO', 'Trabajo Remoto (TR)'), ('OTRO', 'Otro')], max_length=30, verbose_name='Tipo de Permiso'),
        ),
        migrations.AddField(
            model_name='cambiocodigolog',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_log', to='tareo.registrotareo'),
        ),
        migrations.AddField(
            model_name='cambiocodigolog',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
