# Generated by Django 5.1.15 on 2026-04-14 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0029_contrato_one_vigente_per_person'),
        ('tareo', '0033_add_regla_especial_personal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotareo',
            name='almuerzo_manual',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='None=automático (>7h→1h), 0=sin descuento, 0.5, 1.0', max_digits=3, null=True, verbose_name='Almuerzo manual (horas)'),
        ),
        migrations.CreateModel(
            name='ConfiguracionReporteArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails_jefatura', models.JSONField(blank=True, default=list, help_text='Lista de correos principales. Ej: ["jefe@empresa.com"]', verbose_name='Emails jefatura (destinatarios)')),
                ('emails_cc', models.JSONField(blank=True, default=list, help_text='Lista de correos en copia.', verbose_name='Emails con copia (CC)')),
                ('asunto_template', models.CharField(default='Reporte de Asistencia - {area} - {periodo}', help_text='Vars: {area}, {periodo}, {empresa}', max_length=300, verbose_name='Plantilla de asunto')),
                ('cuerpo_template', models.TextField(blank=True, default='', help_text='Vars: {area}, {periodo}, {empresa}, {total_empleados}. Dejar vacío para usar el predeterminado.', verbose_name='Plantilla de cuerpo del correo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_reporte', to='personal.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Configuración Reporte por Área',
                'verbose_name_plural': 'Configuraciones Reporte por Área',
                'ordering': ['area__nombre'],
            },
        ),
        migrations.CreateModel(
            name='EnvioReporteArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_periodo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('PERSONALIZADO', 'Personalizado')], default='PERSONALIZADO', max_length=20)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('emails_destino', models.JSONField(default=list)),
                ('emails_cc', models.JSONField(default=list)),
                ('asunto', models.CharField(blank=True, max_length=300)),
                ('cuerpo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('PARCIAL', 'Enviado con errores'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('empleados_total', models.PositiveIntegerField(default=0)),
                ('empleados_enviados', models.PositiveIntegerField(default=0)),
                ('errores', models.JSONField(default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_reporte', to='personal.area', verbose_name='Área')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_reporte_area', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envío de Reporte por Área',
                'verbose_name_plural': 'Envíos de Reporte por Área',
                'ordering': ['-creado_en'],
            },
        ),
    ]
