# Generated by Django 5.1.15 on 2026-04-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0034_configuracion_reporte_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionreportearea',
            name='historial_emails',
            field=models.JSONField(blank=True, default=list, help_text='Registro automático de cada vez que se cambian los destinatarios', verbose_name='Historial de cambios de emails'),
        ),
        migrations.AddField(
            model_name='configuracionreportearea',
            name='nombre_jefe',
            field=models.CharField(blank=True, default='', help_text='Nombre de referencia para mostrar en el panel', max_length=200, verbose_name='Nombre del jefe / responsable'),
        ),
    ]
