# Generated by Django 5.1.15 on 2026-03-02 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=200, verbose_name='Servidor SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Puerto')),
                ('smtp_user', models.CharField(blank=True, max_length=200, verbose_name='Usuario SMTP')),
                ('smtp_password', models.CharField(blank=True, max_length=200, verbose_name='Contraseña SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('email_from', models.EmailField(blank=True, max_length=254, verbose_name='Email remitente')),
                ('email_reply_to', models.EmailField(blank=True, max_length=254, verbose_name='Email de respuesta')),
                ('firma_html', models.TextField(blank=True, help_text='Firma HTML que se agrega al final de cada email', verbose_name='Firma HTML')),
                ('activa', models.BooleanField(default=False, help_text='Activar para habilitar el envío de emails', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Configuración SMTP',
                'verbose_name_plural': 'Configuración SMTP',
            },
        ),
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('codigo', models.SlugField(help_text='Identificador único (slug). Ej: bienvenida_onboarding', max_length=100, unique=True, verbose_name='Código')),
                ('asunto_template', models.CharField(help_text='Admite sintaxis Django: {{ nombre }}, {{ fecha }}, etc.', max_length=200, verbose_name='Asunto (template)')),
                ('cuerpo_template', models.TextField(help_text='HTML con variables Django: {{ nombre }}, {{ cargo }}, {{ empresa }}, etc.', verbose_name='Cuerpo (template HTML)')),
                ('tipo', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App'), ('AMBOS', 'Ambos')], default='IN_APP', max_length=10, verbose_name='Canal de envío')),
                ('modulo', models.CharField(choices=[('RRHH', 'RRHH'), ('ASISTENCIA', 'Asistencia'), ('ONBOARDING', 'Onboarding'), ('VACACIONES', 'Vacaciones'), ('DISCIPLINARIA', 'Disciplinaria'), ('EVALUACIONES', 'Evaluaciones'), ('ENCUESTAS', 'Encuestas'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20, verbose_name='Módulo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('variables_disponibles', models.TextField(blank=True, help_text='Documentación de variables: {{ nombre }}, {{ fecha }}, {{ cargo }}, {{ empresa }}, {{ url }}', verbose_name='Variables disponibles')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificación',
                'ordering': ['modulo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComunicadoMasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo (HTML)')),
                ('tipo', models.CharField(choices=[('COMUNICADO', 'Comunicado'), ('MEMO', 'Memo'), ('POLITICA', 'Política'), ('AVISO', 'Aviso')], default='COMUNICADO', max_length=15, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROGRAMADO', 'Programado'), ('ENVIADO', 'Enviado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=12, verbose_name='Estado')),
                ('destinatarios_tipo', models.CharField(choices=[('TODOS', 'Todos'), ('AREA', 'Por Área'), ('GRUPO', 'Por Grupo'), ('INDIVIDUAL', 'Individual')], default='TODOS', max_length=12, verbose_name='Tipo de destinatarios')),
                ('grupo', models.CharField(blank=True, choices=[('STAFF', 'STAFF'), ('RCO', 'RCO')], help_text="Solo si el tipo de destinatarios es 'Por Grupo'", max_length=10, verbose_name='Grupo')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='comunicaciones/adjuntos/%Y/%m/', verbose_name='Adjunto')),
                ('requiere_confirmacion', models.BooleanField(default=False, verbose_name='Requiere confirmación de lectura')),
                ('programado_para', models.DateTimeField(blank=True, null=True, verbose_name='Programado para')),
                ('enviado_en', models.DateTimeField(blank=True, null=True, verbose_name='Enviado en')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(blank=True, help_text="Solo si el tipo de destinatarios es 'Por Área'", to='personal.area', verbose_name='Áreas')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('personal_individual', models.ManyToManyField(blank=True, related_name='comunicados_directos', to='personal.personal', verbose_name='Personal individual')),
            ],
            options={
                'verbose_name': 'Comunicado Masivo',
                'verbose_name_plural': 'Comunicados Masivos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibir_email', models.BooleanField(default=True, verbose_name='Recibir emails')),
                ('recibir_in_app', models.BooleanField(default=True, verbose_name='Recibir notificaciones in-app')),
                ('frecuencia_resumen', models.CharField(choices=[('INMEDIATO', 'Inmediato'), ('DIARIO', 'Resumen diario'), ('SEMANAL', 'Resumen semanal')], default='INMEDIATO', max_length=10, verbose_name='Frecuencia de resumen')),
                ('horario_silencio_inicio', models.TimeField(blank=True, null=True, verbose_name='Silencio desde')),
                ('horario_silencio_fin', models.TimeField(blank=True, null=True, verbose_name='Silencio hasta')),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_notificacion', to='personal.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
            },
        ),
        migrations.CreateModel(
            name='ConfirmacionLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de lectura')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('confirmado', models.BooleanField(default=True, verbose_name='Confirmado')),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='comunicaciones.comunicadomasivo', verbose_name='Comunicado')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones_comunicados', to='personal.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Confirmación de Lectura',
                'verbose_name_plural': 'Confirmaciones de Lectura',
                'ordering': ['-fecha_lectura'],
                'unique_together': {('comunicado', 'personal')},
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario_email', models.EmailField(blank=True, help_text='Usado cuando el destinatario no tiene registro en Personal', max_length=254, verbose_name='Email destinatario')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo (HTML)')),
                ('tipo', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App')], default='IN_APP', max_length=10, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('FALLIDA', 'Fallida'), ('LEIDA', 'Leída')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('enviada_en', models.DateTimeField(blank=True, null=True, verbose_name='Enviada en')),
                ('leida_en', models.DateTimeField(blank=True, null=True, verbose_name='Leída en')),
                ('error_detalle', models.TextField(blank=True, verbose_name='Detalle de error')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos extra de contexto en formato JSON', verbose_name='Metadatos')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='personal.personal', verbose_name='Destinatario')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_generadas', to='comunicaciones.plantillanotificacion', verbose_name='Plantilla usada')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['destinatario', 'tipo', 'estado'], name='comunicacio_destina_caa43d_idx'), models.Index(fields=['-creado_en'], name='comunicacio_creado__e5297f_idx'), models.Index(fields=['estado'], name='comunicacio_estado_bdb9df_idx')],
            },
        ),
    ]
