import pathlib,base64
b = chr(123)+chr(37)
e = chr(37)+chr(125)
q = chr(34)
sq = chr(39)
nl = chr(10)
def tag(x): return b+" "+x+" "+e
lines = []
w = lines.append
w(b+" extends "+q+"base.html"+q+" "+e)
w(b+" load humanize "+e)
w("")
w(tag("block title")+"Notificaciones"+tag("endblock"))
w("")
w(tag("block content"))
w("<div class="+q+"d-flex justify-content-between align-items-center mb-3"+q+">")
w("    <div>")
w("        <h2 class="+q+"mb-0"+q+"><i class="+q+"fas fa-bell text-secondary me-2"+q+"></i>{{ titulo }}</h2>")
w("        <small class="+q+"text-muted"+q+">Motor de notificaciones de Harmoni</small>")
w("    </div>")
w("</div>")
w("")
# KPI strip
w("<div class="+q+"row g-3 mb-4"+q+">")
w("")
def kpi(col,val,label,cls="",color=""):
    sty=" style="+q+"color:"+color+";"+q if color else ""
    ca=" class="+q+"fs-3 fw-bold "+cls+q if cls else " class="+q+"fs-3 fw-bold"+q
    w("    <div class="+q+col+q+">")
    w("        <div class="+q+"card h-100 border-0 shadow-sm"+q+">")
    w("            <div class="+q+"card-body p-3 text-center"+q+">")
    w("                <div"+ca+sty+">"+val+"</div>")
    w("                <div class="+q+"small text-muted mt-1"+q+">"+label+"</div>")
    w("            </div>")
    w("        </div>")
    w("    </div>")
    w("")
kpi("col-6 col-sm-4 col-lg-2","{{ total_notifs|intcomma }}","Total notificaciones","text-primary")
kpi("col-6 col-sm-4 col-lg-2","{{ enviadas_mes|intcomma }}","Enviadas este mes",color="#0f766e")
kpi("col-6 col-sm-4 col-lg-2","{{ tasa_lectura_pct }}%","Tasa de lectura",color="#5eead4")
kpi("col-6 col-sm-4 col-lg-2","{{ total_comunicados|intcomma }}","Comunicados enviados","text-info")
kpi("col-6 col-sm-4 col-lg-2","{{ pendientes_in_app|intcomma }}","In-App sin leer","text-warning")
kpi("col-6 col-sm-4 col-lg-2","{{ fallidas|intcomma }}","Fallidas","text-danger")
w("</div>")
w("")
# Analytics row
w("<div class="+q+"row g-3 mb-4"+q+">")
w("")
w("    <div class="+q+"col-12 col-md-4"+q+">")
w("        <div class="+q+"card border-0 shadow-sm h-100"+q+">")
w("            <div class="+q+"card-header bg-white border-0 pb-0"+q+">")
w("                <span class="+q+"fw-semibold small text-muted text-uppercase"+q+" style="+q+"letter-spacing:.05em;"+q+">Distribuci&oacute;n por tipo</span>")
w("            </div>")
w("            <div class="+q+"card-body d-flex flex-column align-items-center justify-content-center"+q+">")
w("                <div style="+q+"position:relative;height:190px;width:100%;"+q+"><canvas id="+q+"chartTipo"+q+"></canvas></div>")
w("            </div>")
w("        </div>")
w("    </div>")
w("")
w("    <div class="+q+"col-12 col-md-5"+q+">")
w("        <div class="+q+"card border-0 shadow-sm h-100"+q+">")
w("            <div class="+q+"card-header bg-white border-0 pb-0"+q+">")
w("                <span class="+q+"fw-semibold small text-muted text-uppercase"+q+" style="+q+"letter-spacing:.05em;"+q+">Tendencia &mdash; &uacute;ltimos 6 meses</span>")
w("            </div>")
w("            <div class="+q+"card-body"+q+">")
w("                <div style="+q+"position:relative;height:190px;width:100%;"+q+"><canvas id="+q+"chartTrend"+q+"></canvas></div>")
w("            </div>")
w("        </div>")
w("    </div>")
w("")
