# Generated by Django 5.1.15 on 2026-03-02 05:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('icono', models.CharField(default='fa-chalkboard-teacher', max_length=50)),
                ('color', models.CharField(default='primary', max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=10)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Capacitación',
                'verbose_name_plural': 'Categorías de Capacitación',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('ASISTIO', 'Asistió'), ('NO_ASISTIO', 'No Asistió'), ('PARCIAL', 'Asistencia Parcial')], default='INSCRITO', max_length=12)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota/Calificación')),
                ('aprobado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='capacitaciones/certificados/%Y/%m/', verbose_name='Certificado')),
                ('fecha_certificado', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_capacitacion', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Asistencia a Capacitación',
                'verbose_name_plural': 'Asistencias a Capacitaciones',
                'ordering': ['personal__apellidos_nombres'],
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa'), ('ELEARNING', 'E-Learning'), ('INDUCCION', 'Inducción'), ('SSOMA', 'SSOMA')], default='INTERNA', max_length=12)),
                ('instructor', models.CharField(blank=True, max_length=200, verbose_name='Instructor/Proveedor')),
                ('lugar', models.CharField(blank=True, max_length=200, verbose_name='Lugar')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('horas', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))], verbose_name='Horas')),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo (S/)')),
                ('max_participantes', models.PositiveSmallIntegerField(default=0, help_text='0 = sin límite', verbose_name='Máx. Participantes')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=12)),
                ('obligatoria', models.BooleanField(default=False, help_text='Si es obligatoria, aparecerá como pendiente en incumplimientos')),
                ('material_url', models.URLField(blank=True, verbose_name='URL Material')),
                ('material_archivo', models.FileField(blank=True, null=True, upload_to='capacitaciones/material/%Y/%m/', verbose_name='Material (archivo)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='capacitaciones_asignadas', through='capacitaciones.AsistenciaCapacitacion', to='personal.personal')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacitaciones', to='capacitaciones.categoriacapacitacion')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='asistenciacapacitacion',
            name='capacitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='capacitaciones.capacitacion'),
        ),
        migrations.CreateModel(
            name='RequerimientoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Requerimiento')),
                ('descripcion', models.TextField(blank=True)),
                ('aplica_todos', models.BooleanField(default=False, help_text='Aplica a todo el personal activo')),
                ('aplica_staff', models.BooleanField(default=True)),
                ('aplica_rco', models.BooleanField(default=True)),
                ('frecuencia', models.CharField(choices=[('UNICA', 'Única vez'), ('ANUAL', 'Anual'), ('SEMESTRAL', 'Semestral'), ('TRIMESTRAL', 'Trimestral')], default='ANUAL', max_length=12)),
                ('horas_minimas', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=5, verbose_name='Horas Mínimas')),
                ('vigencia_dias', models.PositiveIntegerField(default=365, help_text='Días de vigencia de la capacitación antes de requerir recertificación', verbose_name='Vigencia (días)')),
                ('base_legal', models.CharField(blank=True, max_length=200)),
                ('obligatorio', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aplica_areas', models.ManyToManyField(blank=True, related_name='requerimientos_capacitacion', to='personal.area', verbose_name='Áreas Aplica')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos', to='capacitaciones.categoriacapacitacion')),
            ],
            options={
                'verbose_name': 'Requerimiento de Capacitación',
                'verbose_name_plural': 'Requerimientos de Capacitación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CertificacionTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtencion', models.DateField(verbose_name='Fecha Obtención')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('POR_VENCER', 'Por Vencer'), ('VENCIDA', 'Vencida'), ('REVOCADA', 'Revocada')], default='VIGENTE', max_length=12)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='capacitaciones/certs/%Y/%m/', verbose_name='Certificado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('capacitacion', models.ForeignKey(blank=True, help_text='Capacitación que generó esta certificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificaciones_generadas', to='capacitaciones.capacitacion')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='personal.personal')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='capacitaciones.requerimientocapacitacion')),
            ],
            options={
                'verbose_name': 'Certificación del Trabajador',
                'verbose_name_plural': 'Certificaciones de Trabajadores',
                'ordering': ['-fecha_obtencion'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='asistenciacapacitacion',
            unique_together={('capacitacion', 'personal')},
        ),
        migrations.AddIndex(
            model_name='capacitacion',
            index=models.Index(fields=['-fecha_inicio'], name='capacitacio_fecha_i_1be611_idx'),
        ),
        migrations.AddIndex(
            model_name='capacitacion',
            index=models.Index(fields=['estado', 'tipo'], name='capacitacio_estado_ea0a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaciontrabajador',
            index=models.Index(fields=['personal', 'estado'], name='capacitacio_persona_cff27f_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaciontrabajador',
            index=models.Index(fields=['fecha_vencimiento'], name='capacitacio_fecha_v_44fa28_idx'),
        ),
    ]
