# Generated by Django 5.1.15 on 2026-03-02 05:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.SlugField(unique=True, verbose_name='Codigo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('color', models.CharField(default='#94a3b8', help_text='Color hexadecimal para la columna', max_length=7, verbose_name='Color')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('eliminable', models.BooleanField(default=True, help_text='Las etapas del sistema no pueden eliminarse', verbose_name='Eliminable')),
            ],
            options={
                'verbose_name': 'Etapa del Pipeline',
                'verbose_name_plural': 'Etapas del Pipeline',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=250, verbose_name='Nombre Completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electronico')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Telefono')),
                ('cv', models.FileField(blank=True, null=True, upload_to='reclutamiento/cvs/', verbose_name='CV')),
                ('experiencia_anos', models.PositiveIntegerField(default=0, verbose_name='Anios de Experiencia')),
                ('educacion', models.CharField(choices=[('NO_REQUERIDO', 'No Requerido'), ('SECUNDARIA', 'Secundaria'), ('TECNICO', 'Tecnico'), ('UNIVERSITARIO', 'Universitario'), ('MAESTRIA', 'Maestria'), ('DOCTORADO', 'Doctorado')], default='NO_REQUERIDO', max_length=15, verbose_name='Nivel Educativo')),
                ('salario_pretendido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario Pretendido')),
                ('fuente', models.CharField(choices=[('PORTAL', 'Portal de Empleo'), ('LINKEDIN', 'LinkedIn'), ('REFERIDO', 'Referido'), ('HEADHUNTER', 'Headhunter'), ('OTRO', 'Otro')], default='PORTAL', max_length=12, verbose_name='Fuente')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('DESCARTADA', 'Descartada'), ('CONTRATADA', 'Contratada')], default='ACTIVA', max_length=12, verbose_name='Estado')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Postulacion')),
                ('etapa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones', to='reclutamiento.etapapipeline', verbose_name='Etapa Actual')),
                ('personal_creado', models.ForeignKey(blank=True, help_text='Vinculo al registro de Personal si fue contratado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulacion_origen', to='personal.personal', verbose_name='Personal Creado')),
            ],
            options={
                'verbose_name': 'Postulacion',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-fecha_postulacion'],
            },
        ),
        migrations.CreateModel(
            name='NotaPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('NOTA', 'Nota'), ('ENTREVISTA', 'Entrevista'), ('EVALUACION', 'Evaluacion'), ('REFERENCIA', 'Referencia')], default='NOTA', max_length=12, verbose_name='Tipo')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_detalle', to='reclutamiento.postulacion', verbose_name='Postulacion')),
            ],
            options={
                'verbose_name': 'Nota de Postulacion',
                'verbose_name_plural': 'Notas de Postulacion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EntrevistaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('duracion_minutos', models.PositiveIntegerField(default=60, verbose_name='Duracion (minutos)')),
                ('tipo', models.CharField(choices=[('RRHH', 'RRHH'), ('TECNICA', 'Tecnica'), ('GERENCIAL', 'Gerencial'), ('GRUPAL', 'Grupal')], default='RRHH', max_length=10, verbose_name='Tipo')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('TELEFONICA', 'Telefonica')], default='PRESENCIAL', max_length=12, verbose_name='Modalidad')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicacion')),
                ('enlace_virtual', models.URLField(blank=True, help_text='Link de Meet, Zoom, Teams, etc.', verbose_name='Enlace Virtual')),
                ('notas_pre', models.TextField(blank=True, help_text='Puntos a evaluar, preguntas clave', verbose_name='Notas Previas')),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REPROGRAMAR', 'Reprogramar')], default='PENDIENTE', max_length=12, verbose_name='Resultado')),
                ('calificacion', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Calificacion (1-10)')),
                ('notas_post', models.TextField(blank=True, help_text='Observaciones y conclusiones', verbose_name='Notas Post-Entrevista')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('entrevistador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevistas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Entrevistador')),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='reclutamiento.postulacion', verbose_name='Postulacion')),
            ],
            options={
                'verbose_name': 'Entrevista Programada',
                'verbose_name_plural': 'Entrevistas Programadas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo del Puesto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('requisitos', models.TextField(blank=True, verbose_name='Requisitos')),
                ('experiencia_minima', models.PositiveIntegerField(default=0, help_text='Anios de experiencia requeridos', verbose_name='Experiencia Minima (anios)')),
                ('educacion_minima', models.CharField(choices=[('NO_REQUERIDO', 'No Requerido'), ('SECUNDARIA', 'Secundaria'), ('TECNICO', 'Tecnico'), ('UNIVERSITARIO', 'Universitario'), ('MAESTRIA', 'Maestria'), ('DOCTORADO', 'Doctorado')], default='NO_REQUERIDO', max_length=15, verbose_name='Educacion Minima')),
                ('tipo_contrato', models.CharField(choices=[('INDETERMINADO', 'Plazo Indeterminado'), ('PLAZO_FIJO', 'Plazo Fijo'), ('PROYECTO', 'Por Proyecto'), ('SUPLENCIA', 'Suplencia')], default='INDETERMINADO', max_length=15, verbose_name='Tipo de Contrato')),
                ('salario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salario Minimo')),
                ('salario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salario Maximo')),
                ('moneda', models.CharField(choices=[('PEN', 'PEN'), ('USD', 'USD')], default='PEN', max_length=3, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('EN_PROCESO', 'En Proceso'), ('CUBIERTA', 'Cubierta'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=12, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicacion')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Limite')),
                ('publica', models.BooleanField(default=False, help_text='Si esta marcada, aparece en la pagina publica de empleo', verbose_name='Visible en Portal de Empleo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes', to='personal.area', verbose_name='Area')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='postulacion',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='reclutamiento.vacante', verbose_name='Vacante'),
        ),
        migrations.AddIndex(
            model_name='vacante',
            index=models.Index(fields=['estado'], name='reclutamien_estado_5058d5_idx'),
        ),
        migrations.AddIndex(
            model_name='vacante',
            index=models.Index(fields=['area'], name='reclutamien_area_id_f06587_idx'),
        ),
        migrations.AddIndex(
            model_name='vacante',
            index=models.Index(fields=['prioridad'], name='reclutamien_priorid_a57dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='vacante',
            index=models.Index(fields=['-creado_en'], name='reclutamien_creado__71c218_idx'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['vacante', 'estado'], name='reclutamien_vacante_923c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['etapa'], name='reclutamien_etapa_i_2bac43_idx'),
        ),
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['-fecha_postulacion'], name='reclutamien_fecha_p_fd49dc_idx'),
        ),
    ]
