# Generated by Django 5.1.15 on 2026-03-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_personal_grupo_tareo_condicion_codigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='asignacion_familiar',
            field=models.BooleanField(default=False, help_text='Percibe 10% RMV por hijo(s) menor(es)', verbose_name='Asignación Familiar'),
        ),
        migrations.AddField(
            model_name='personal',
            name='categoria',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('CONFIANZA', 'Personal de Confianza'), ('DIRECCION', 'Personal de Dirección')], default='NORMAL', help_text='Confianza/Dirección: excluidos de jornada máxima (D.Leg. 854 art.5). Sin HE ni control de faltas.', max_length=12, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='personal',
            name='cuspp',
            field=models.CharField(blank=True, help_text='Código Único del SPP (solo AFP)', max_length=20, verbose_name='CUSPP'),
        ),
        migrations.AddField(
            model_name='personal',
            name='regimen_pension',
            field=models.CharField(choices=[('AFP', 'AFP'), ('ONP', 'ONP'), ('SIN_PENSION', 'Sin Régimen')], default='AFP', max_length=12, verbose_name='Régimen Pensionario'),
        ),
    ]
