# Generated by Django 5.1.15 on 2026-03-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='fecha_fin_contrato',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento. Vacío = indefinido o sin fecha pactada.', null=True, verbose_name='Vencimiento del contrato'),
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_inicio_contrato',
            field=models.DateField(blank=True, help_text='Fecha de inicio del contrato actual', null=True, verbose_name='Inicio del contrato vigente'),
        ),
        migrations.AddField(
            model_name='personal',
            name='observaciones_contrato',
            field=models.TextField(blank=True, verbose_name='Observaciones del contrato'),
        ),
        migrations.AddField(
            model_name='personal',
            name='renovacion_automatica',
            field=models.BooleanField(default=False, help_text='Marcar si el contrato se renueva automáticamente al vencer', verbose_name='Renovación automática'),
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('INDEFINIDO', 'Contrato Indefinido'), ('PLAZO_FIJO', 'Contrato a Plazo Fijo (Modal)'), ('INICIO_ACTIVIDAD', 'Inicio de Actividad'), ('NECESIDAD_MERCADO', 'Necesidad de Mercado'), ('RECONVERSION_EMPRESARIAL', 'Reconversión Empresarial'), ('OBRA_SERVICIO', 'Para Obra o Servicio'), ('DISCONTINUO', 'Intermitente / Discontinuo'), ('TEMPORADA', 'De Temporada'), ('SUPLENCIA', 'De Suplencia'), ('EMERGENCIA', 'Emergencia Accidental'), ('SNP', 'Locación de Servicios (SNP)'), ('PRACTICANTE', 'Practicante Pre/Profesional'), ('OTRO', 'Otro')], help_text='Modalidad contractual según D.Leg. 728', max_length=25, verbose_name='Modalidad de Contrato'),
        ),
    ]
