# Generated by Django 5.1.15 on 2026-03-02 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_add_contrato_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código interno o de centro de costo (ej: ADM, OPS-01, GG)', max_length=20, verbose_name='Código / Centro de Costo'),
        ),
        migrations.AddField(
            model_name='area',
            name='jefe_area',
            field=models.ForeignKey(blank=True, help_text='Responsable principal del área (jefe inmediato SUNAT)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_jefatura', to='personal.personal', verbose_name='Jefe de Área'),
        ),
        migrations.AlterField(
            model_name='area',
            name='responsables',
            field=models.ManyToManyField(blank=True, help_text='Personas con acceso de gestión al área (además del jefe)', related_name='areas_responsable', to='personal.personal', verbose_name='Responsables adicionales'),
        ),
    ]
