# Generated by Django 5.1.15 on 2026-03-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_area_codigo_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='motivo_cese',
            field=models.CharField(blank=True, choices=[('RENUNCIA', 'Renuncia voluntaria'), ('MUTUO_ACUERDO', 'Mutuo acuerdo'), ('JUBILACION', 'Jubilacion'), ('VENCIMIENTO', 'Vencimiento de contrato'), ('NO_RENOVACION', 'No renovacion'), ('DESPIDO_CAUSA', 'Despido con causa justificada'), ('CESE_COLECTIVO', 'Cese colectivo'), ('LIQUIDACION', 'Liquidacion / Disolucion empresa'), ('FALLECIMIENTO', 'Fallecimiento'), ('INVALIDEZ', 'Invalidez permanente'), ('ABANDONO', 'Abandono de trabajo'), ('OTRO', 'Otro')], help_text='Causa del cese laboral (DS 003-97-TR). Requerido al cesar al trabajador.', max_length=20, verbose_name='Motivo de Cese'),
        ),
    ]
