# Generated by Django 5.1.15 on 2026-03-04 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_add_motivo_cese'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['estado', 'grupo_tareo'], name='personal_estado_grupo_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['estado', 'condicion'], name='personal_estado_condicion_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['estado', 'categoria'], name='personal_estado_categoria_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['fecha_fin_contrato'], name='personal_fin_contrato_idx'),
        ),
    ]
