# Generated by Django 5.1.15 on 2026-03-05 01:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_add_perfil_acceso_to_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='eps_descuento_mensual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Co-pago mensual del trabajador a la EPS. Deducible de la base de IR 5ta (Art. 46° TUO LIR). Cero si el empleador asume el 100% de la prima.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Aporte EPS trabajador (mensual)'),
        ),
        migrations.AddField(
            model_name='personal',
            name='tiene_eps',
            field=models.BooleanField(default=False, help_text='El empleador contrata EPS para este trabajador en lugar de EsSalud. Si el trabajador paga un co-seguro, registrar el monto mensual abajo.', verbose_name='Tiene EPS'),
        ),
        migrations.AddField(
            model_name='personal',
            name='viaticos_mensual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Asignación mensual fija de viáticos. No es remuneración (D.Leg. 728 Art. 19°) y NO forma parte de la base de IR 5ta. Solo para referencia y planilla.', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Viáticos fijos mensuales'),
        ),
    ]
