# Generated by Django 5.1.15 on 2026-03-29 02:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0021_add_missing_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='personal',
            name='personal_fecha_alta_idx',
        ),
        migrations.RemoveIndex(
            model_name='personal',
            name='personal_apellidos_idx',
        ),
        migrations.AlterField(
            model_name='personal',
            name='motivo_cese',
            field=models.CharField(blank=True, choices=[('RENUNCIA', 'Renuncia voluntaria'), ('MUTUO_ACUERDO', 'Mutuo acuerdo'), ('JUBILACION', 'Jubilacion'), ('VENCIMIENTO', 'Vencimiento de contrato'), ('TERMINO_CONTRATO', 'Termino de contrato'), ('NO_RENOVACION', 'No renovacion'), ('DESPIDO_CAUSA', 'Despido con causa justificada'), ('CESE_COLECTIVO', 'Cese colectivo'), ('LIQUIDACION', 'Liquidacion / Disolucion empresa'), ('FALLECIMIENTO', 'Fallecimiento'), ('INVALIDEZ', 'Invalidez permanente'), ('ABANDONO', 'Abandono de trabajo'), ('OTRO', 'Otro')], help_text='Causa del cese laboral (DS 003-97-TR). Requerido al cesar al trabajador.', max_length=20, verbose_name='Motivo de Cese'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='sueldo_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sueldo Base'),
        ),
    ]
