# Generated by Django 5.1.15 on 2026-03-29 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0022_remove_personal_personal_fecha_alta_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='reporta_a',
            field=models.ForeignKey(blank=True, help_text='Superior directo en el organigrama', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='personal.personal', verbose_name='Reporta a'),
        ),
    ]
