# Generated by Django 5.1.15 on 2026-03-29 16:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0023_add_reporta_a_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Contrato Indefinido'), ('PLAZO_FIJO', 'Contrato a Plazo Fijo (Modal)'), ('INICIO_ACTIVIDAD', 'Inicio de Actividad'), ('NECESIDAD_MERCADO', 'Necesidad de Mercado'), ('RECONVERSION_EMPRESARIAL', 'Reconversión Empresarial'), ('OBRA_SERVICIO', 'Para Obra o Servicio'), ('DISCONTINUO', 'Intermitente / Discontinuo'), ('TEMPORADA', 'De Temporada'), ('SUPLENCIA', 'De Suplencia'), ('EMERGENCIA', 'Emergencia Accidental'), ('SNP', 'Locación de Servicios (SNP)'), ('PRACTICANTE', 'Practicante Pre/Profesional'), ('OTRO', 'Otro')], help_text='Según D.Leg. 728 — Ley de Productividad y Competitividad Laboral', max_length=25, verbose_name='Modalidad de Contrato')),
                ('numero_contrato', models.CharField(blank=True, help_text='Código interno o número de registro del contrato', max_length=50, verbose_name='Número de Contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar vacío para contratos indefinidos', null=True, verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('RENOVADO', 'Renovado'), ('RESCINDIDO', 'Rescindido'), ('FINALIZADO', 'Finalizado')], default='VIGENTE', max_length=12, verbose_name='Estado')),
                ('renovacion_automatica', models.BooleanField(default=False, help_text='El contrato se renueva sin trámite al vencer', verbose_name='Renovación automática')),
                ('sueldo_pactado', models.DecimalField(blank=True, decimal_places=2, help_text='Remuneración mensual acordada en el contrato', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sueldo pactado')),
                ('cargo_contrato', models.CharField(blank=True, help_text='Cargo que figura en el contrato (puede diferir del cargo actual)', max_length=150, verbose_name='Cargo en contrato')),
                ('jornada_semanal', models.DecimalField(decimal_places=1, default=Decimal('48.0'), help_text='Jornada máxima legal en Perú: 48 horas semanales (D.Leg. 854)', max_digits=4, verbose_name='Jornada semanal (horas)')),
                ('archivo_pdf', models.FileField(blank=True, help_text='Documento escaneado del contrato firmado', upload_to='contratos/%Y/%m/', verbose_name='Archivo PDF')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='personal.personal', verbose_name='Trabajador')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Adenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de adenda')),
                ('tipo_modificacion', models.CharField(choices=[('SUELDO', 'Modificación de sueldo'), ('CARGO', 'Cambio de cargo / puesto'), ('HORARIO', 'Cambio de horario / jornada'), ('CONDICIONES', 'Cambio de condiciones'), ('EXTENSION', 'Extensión de plazo'), ('AREA', 'Cambio de área / sede'), ('OTRO', 'Otro')], max_length=15, verbose_name='Tipo de modificación')),
                ('detalle', models.TextField(help_text='Describa los cambios realizados al contrato', verbose_name='Detalle de la modificación')),
                ('valor_anterior', models.CharField(blank=True, help_text='Valor o condición antes del cambio', max_length=200, verbose_name='Valor anterior')),
                ('valor_nuevo', models.CharField(blank=True, help_text='Valor o condición después del cambio', max_length=200, verbose_name='Valor nuevo')),
                ('archivo', models.FileField(blank=True, upload_to='adendas/%Y/%m/', verbose_name='Archivo adjunto')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adendas', to='personal.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Adenda',
                'verbose_name_plural': 'Adendas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RenovacionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_renovacion', models.DateField(verbose_name='Fecha de renovación')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de renovación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones_entrantes', to='personal.contrato', verbose_name='Contrato renovado')),
                ('contrato_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones_salientes', to='personal.contrato', verbose_name='Contrato original')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Renovación de Contrato',
                'verbose_name_plural': 'Renovaciones de Contrato',
                'ordering': ['-fecha_renovacion'],
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['personal', '-fecha_inicio'], name='contrato_personal_inicio_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['estado'], name='contrato_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['fecha_fin'], name='contrato_fecha_fin_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['tipo_contrato'], name='contrato_tipo_idx'),
        ),
    ]
