# Generated by Django 5.1.15 on 2026-03-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0024_contrato_adenda_renovacioncontrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la plantilla')),
                ('tipo_contrato', models.CharField(blank=True, choices=[('INDEFINIDO', 'Contrato Indefinido'), ('PLAZO_FIJO', 'Contrato a Plazo Fijo (Modal)'), ('INICIO_ACTIVIDAD', 'Inicio de Actividad'), ('NECESIDAD_MERCADO', 'Necesidad de Mercado'), ('RECONVERSION_EMPRESARIAL', 'Reconversión Empresarial'), ('OBRA_SERVICIO', 'Para Obra o Servicio'), ('DISCONTINUO', 'Intermitente / Discontinuo'), ('TEMPORADA', 'De Temporada'), ('SUPLENCIA', 'De Suplencia'), ('EMERGENCIA', 'Emergencia Accidental'), ('SNP', 'Locación de Servicios (SNP)'), ('PRACTICANTE', 'Practicante Pre/Profesional'), ('OTRO', 'Otro')], help_text='Tipo de contrato al que aplica esta plantilla (vacio = generico)', max_length=25, verbose_name='Tipo de contrato asociado')),
                ('contenido_html', models.TextField(help_text='Usar placeholders: {{nombre_empleado}}, {{cargo}}, {{fecha_inicio}}, {{fecha_fin}}, {{remuneracion}}, {{dni}}, {{empresa}}, {{ruc_empresa}}, {{direccion_empresa}}', verbose_name='Contenido HTML')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Plantilla de Contrato',
                'verbose_name_plural': 'Plantillas de Contrato',
                'ordering': ['nombre'],
            },
        ),
    ]
