# Generated by Django 5.1.15 on 2026-03-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0025_plantillacontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='nivel_org',
            field=models.CharField(blank=True, choices=[('GG', 'Gerente General'), ('CTA', 'Representante Cliente (CTA/KP)'), ('DIR', 'Director / Alta Gerencia'), ('GER', 'Gerente de Área'), ('JEFE_SR', 'Jefe Senior / Subgerente'), ('JEFE', 'Jefe / Coordinador / Responsable'), ('ESP', 'Especialista / Ingeniero / Analista'), ('ASIST', 'Asistente / Técnico / Auxiliar'), ('LIBERTY', 'Liberty (contrato especial)'), ('EXPAT', 'Expatriado')], default='', help_text='Color y jerarquía en el organigrama visual', max_length=10, verbose_name='Nivel Organigrama'),
        ),
        migrations.AddField(
            model_name='personal',
            name='personal_clave',
            field=models.BooleanField(default=False, help_text="Marcado con ícono 'C' en el organigrama", verbose_name='Personal Clave'),
        ),
    ]
