# Generated by Django 5.1.15 on 2026-03-31 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_cargo_model_plantilla_evolution'),
        ('personal', '0026_add_nivel_org_personal_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Cargo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1, 'Alta Dirección'), (2, 'Gerencia'), (3, 'Jefatura / Coordinación'), (4, 'Especialista / Profesional'), (5, 'Técnico / Asistente'), (6, 'Operativo')], default=5, help_text='1=Alta Dirección, 2=Gerencia, 3=Jefatura, 4=Especialista, 5=Técnico, 6=Operativo', verbose_name='Nivel jerárquico')),
                ('funciones', models.TextField(blank=True, help_text='Lista de funciones para insertar en contratos laborales. Una función por línea.', verbose_name='Funciones del cargo')),
                ('es_confianza', models.BooleanField(default=False, help_text='Art. 43 DL 728. No sujeto a fiscalización de jornada. Período de prueba 6 meses.', verbose_name='Personal de confianza')),
                ('es_fiscalizable', models.BooleanField(default=True, help_text='Sujeto a control de asistencia y jornada laboral (48h semanales).', verbose_name='Sujeto a fiscalización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nivel', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='plantillacontrato',
            options={'ordering': ['tipo_documento', 'nombre'], 'verbose_name': 'Plantilla de Contrato', 'verbose_name_plural': 'Plantillas de Contrato'},
        ),
        migrations.AddField(
            model_name='plantillacontrato',
            name='categoria',
            field=models.CharField(blank=True, choices=[('', '--- Sin categoría ---'), ('CONFIANZA', 'Personal de Confianza (no fiscalizable)'), ('FISCALIZABLE', 'Personal Fiscalizable (ordinario)'), ('OBRA_DETERMINADA', 'Obra Determinada (genérico)'), ('INDEFINIDO', 'Indefinido'), ('NECESIDAD_MERCADO', 'Necesidad de Mercado'), ('AUMENTO_SALARIAL', 'Adenda — Aumento Salarial'), ('CAMBIO_CARGO', 'Adenda — Cambio de Cargo'), ('CAMBIO_CONDICIONES', 'Adenda — Cambio de Condiciones')], help_text='Subcategoría para filtrar plantillas (ej: Confianza vs Fiscalizable)', max_length=25, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='plantillacontrato',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Si se asigna, esta plantilla solo aplica a esta empresa. Vacío = todas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_contrato', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='plantillacontrato',
            name='tipo_documento',
            field=models.CharField(choices=[('CONTRATO', 'Contrato'), ('PRORROGA', 'Prórroga'), ('ADENDA', 'Adenda'), ('RENOVACION', 'Renovación')], default='CONTRATO', max_length=15, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='plantillacontrato',
            name='contenido_html',
            field=models.TextField(help_text='Placeholders disponibles: {{nombre_empleado}}, {{cargo}}, {{funciones_cargo}}, {{fecha_inicio}}, {{fecha_fin}}, {{remuneracion}}, {{remuneracion_letras}}, {{dni}}, {{tipo_doc_trabajador}}, {{domicilio}}, {{distrito}}, {{provincia}}, {{departamento}}, {{email_trabajador}}, {{empresa}}, {{ruc_empresa}}, {{direccion_empresa}}, {{representante_legal}}, {{cargo_representante}}, {{tipo_doc_representante}}, {{nro_doc_representante}}, {{jornada_semanal}}, {{periodo_prueba}}, {{fecha_inicio_original}}, {{fecha_fin_anterior}}, {{sueldo_anterior}}, {{sueldo_nuevo}}, {{cargo_anterior}}, {{cargo_nuevo}}, {{obra_nombre}}, {{obra_cliente}}, {{logo}}, {{firma_representante}}, {{fecha_firma}}, {{ciudad_firma}}', verbose_name='Contenido HTML'),
        ),
        migrations.AddIndex(
            model_name='plantillacontrato',
            index=models.Index(fields=['tipo_documento', 'categoria', 'activo'], name='personal_pl_tipo_do_deed14_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['nivel', 'nombre'], name='personal_ca_nivel_4e1f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['activo'], name='personal_ca_activo_347534_idx'),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['es_confianza'], name='personal_ca_es_conf_d7f28b_idx'),
        ),
        migrations.AddField(
            model_name='personal',
            name='cargo_obj',
            field=models.ForeignKey(blank=True, help_text='Cargo del catálogo. Usado para funciones en contratos y organigrama.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_asignado', to='personal.cargo', verbose_name='Cargo (normalizado)'),
        ),
    ]
