# Generated by Django 5.1.15 on 2026-03-31 19:33
# Data migration: populate Cargo model from existing Personal.cargo values

import unicodedata
from django.db import migrations


def normalize_cargo_name(name):
    """Normaliza nombre de cargo: title case, sin duplicados de tildes."""
    name = name.strip()
    # Normalize unicode (NFC)
    name = unicodedata.normalize('NFC', name)
    # Title case
    name = name.title()
    # Fix common patterns after title()
    replacements = {
        ' De ': ' de ',
        ' Del ': ' del ',
        ' En ': ' en ',
        ' La ': ' la ',
        ' Las ': ' las ',
        ' Los ': ' los ',
        ' El ': ' el ',
        ' Y ': ' y ',
        ' E ': ' e ',
        ' A ': ' a ',
        ' Por ': ' por ',
        ' Para ': ' para ',
        ' Con ': ' con ',
        'Bim': 'BIM',
        'Ssoma': 'SSOMA',
        'Ti': 'TI',
        'Pvc': 'PVC',
        'Rrhh': 'RRHH',
    }
    for old, new in replacements.items():
        name = name.replace(old, new)
    return name


def assign_nivel(name):
    """Asigna nivel jerárquico basado en keywords del cargo."""
    upper = name.upper()
    if any(k in upper for k in ['GERENTE GENERAL', 'DIRECTOR DE PROYECTO', 'DIRECTOR GENERAL']):
        return 1  # Alta Dirección
    if any(k in upper for k in ['GERENTE', 'DIRECTOR']):
        return 2  # Gerencia
    if any(k in upper for k in ['JEFE', 'COORDINADOR', 'SUPERVISOR', 'RESIDENTE DE OBRA',
                                 'SUPERINTENDENTE', 'BIM MANAGER', 'COMMISIONING MANAGER']):
        return 3  # Jefatura
    if any(k in upper for k in ['INGENIERO', 'ANALISTA', 'ESPECIALISTA', 'CONTADOR',
                                 'ARQUITECTO', 'RESPONSABLE', 'TRABAJADORA SOCIAL']):
        return 4  # Especialista
    if any(k in upper for k in ['ASISTENTE', 'TECNICO', 'TÉCNICO', 'TOPOGRAFO',
                                 'TOPÓGRAFO', 'MODELADOR', 'CADISTA', 'CONTROL',
                                 'SECRETARIA', 'TESORERA', 'CONDUCTOR']):
        return 5  # Técnico
    # Operativos: capataz, operador, operario, auxiliar, instalador, aplicador
    return 6


def is_confianza(name):
    """Determina si el cargo es de confianza (Art. 43 DL 728)."""
    upper = name.upper()
    return any(k in upper for k in [
        'GERENTE', 'DIRECTOR', 'RESIDENTE DE OBRA', 'JEFE',
        'BIM MANAGER', 'COMMISIONING MANAGER',
    ])


def populate_cargos(apps, schema_editor):
    Personal = apps.get_model('personal', 'Personal')
    Cargo = apps.get_model('personal', 'Cargo')

    # Get distinct cargo values
    cargos_raw = (
        Personal.objects
        .exclude(cargo='')
        .exclude(cargo__isnull=True)
        .values_list('cargo', flat=True)
        .distinct()
    )

    # Normalize and deduplicate
    seen = {}  # normalized_upper -> (normalized_name, raw_names)
    for raw in cargos_raw:
        normalized = normalize_cargo_name(raw)
        key = normalized.upper()
        if key not in seen:
            seen[key] = normalized
        # Keep the first normalized version

    # Create Cargo objects
    cargo_map = {}  # uppercase key -> Cargo instance
    for key, name in seen.items():
        cargo = Cargo.objects.create(
            nombre=name,
            nivel=assign_nivel(name),
            es_confianza=is_confianza(name),
            es_fiscalizable=not is_confianza(name),
        )
        cargo_map[key] = cargo

    # Link Personal.cargo_obj
    for personal in Personal.objects.exclude(cargo='').exclude(cargo__isnull=True):
        normalized = normalize_cargo_name(personal.cargo)
        key = normalized.upper()
        if key in cargo_map:
            personal.cargo_obj = cargo_map[key]
            personal.save(update_fields=['cargo_obj'])


def reverse_populate(apps, schema_editor):
    """Reverse: just unlink cargo_obj, don't delete Cargo records."""
    Personal = apps.get_model('personal', 'Personal')
    Personal.objects.update(cargo_obj=None)


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0027_cargo_model_plantilla_evolution'),
    ]

    operations = [
        migrations.RunPython(populate_cargos, reverse_populate),
    ]
