# Generated by Django 5.1.15 on 2026-04-02 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0028_populate_cargo_from_personal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'VIGENTE')), fields=('personal',), name='personal_contrato_one_vigente_per_person'),
        ),
    ]
