# Generated by Django 5.1.15 on 2026-04-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0029_contrato_one_vigente_per_person'),
        ('personal', '0030_activoasignado'),
    ]

    operations = [
    ]
