# Generated by Django 5.1.15 on 2026-03-02 05:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaOffboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Offboarding',
                'verbose_name_plural': 'Plantillas de Offboarding',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PasoPlantillaOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('TAREA', 'Tarea'), ('DOCUMENTO', 'Documento'), ('CAPACITACION', 'Capacitación'), ('NOTIFICACION', 'Notificación'), ('APROBACION', 'Aprobación')], default='TAREA', max_length=15, verbose_name='Tipo')),
                ('responsable_tipo', models.CharField(choices=[('RRHH', 'RRHH'), ('JEFE', 'Jefe Directo'), ('TI', 'TI / Sistemas'), ('TRABAJADOR', 'Trabajador')], default='RRHH', max_length=15, verbose_name='Responsable')),
                ('dias_plazo', models.PositiveSmallIntegerField(default=1, help_text='Días calendario para completar este paso desde la fecha de cese', verbose_name='Días de Plazo')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='onboarding.plantillaoffboarding', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Paso de Plantilla Offboarding',
                'verbose_name_plural': 'Pasos de Plantilla Offboarding',
                'ordering': ['plantilla', 'orden'],
                'unique_together': {('plantilla', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='PlantillaOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('aplica_grupo', models.CharField(choices=[('STAFF', 'STAFF'), ('RCO', 'RCO'), ('TODOS', 'Todos')], default='TODOS', help_text='Grupo de tareo al que aplica esta plantilla', max_length=10, verbose_name='Aplica a Grupo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aplica_areas', models.ManyToManyField(blank=True, help_text='Dejar vacío para aplicar a todas las áreas', related_name='plantillas_onboarding', to='personal.area', verbose_name='Aplica a Áreas')),
            ],
            options={
                'verbose_name': 'Plantilla de Onboarding',
                'verbose_name_plural': 'Plantillas de Onboarding',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PasoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('TAREA', 'Tarea'), ('DOCUMENTO', 'Documento'), ('CAPACITACION', 'Capacitación'), ('NOTIFICACION', 'Notificación'), ('APROBACION', 'Aprobación')], default='TAREA', max_length=15, verbose_name='Tipo')),
                ('responsable_tipo', models.CharField(choices=[('RRHH', 'RRHH'), ('JEFE', 'Jefe Directo'), ('TI', 'TI / Sistemas'), ('TRABAJADOR', 'Trabajador')], default='RRHH', max_length=15, verbose_name='Responsable')),
                ('dias_plazo', models.PositiveSmallIntegerField(default=1, help_text='Días calendario para completar este paso desde la fecha de ingreso', verbose_name='Días de Plazo')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='onboarding.plantillaonboarding', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Paso de Plantilla Onboarding',
                'verbose_name_plural': 'Pasos de Plantilla Onboarding',
                'ordering': ['plantilla', 'orden'],
                'unique_together': {('plantilla', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='ProcesoOffboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cese', models.DateField(verbose_name='Fecha de Cese')),
                ('motivo_cese', models.CharField(choices=[('RENUNCIA', 'Renuncia Voluntaria'), ('DESPIDO', 'Despido'), ('MUTUO_ACUERDO', 'Mutuo Acuerdo'), ('FIN_CONTRATO', 'Fin de Contrato'), ('JUBILACION', 'Jubilación')], max_length=15, verbose_name='Motivo de Cese')),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En Curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='EN_CURSO', max_length=12, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboardings_iniciados', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_offboarding', to='personal.personal', verbose_name='Trabajador')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='onboarding.plantillaoffboarding', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Proceso de Offboarding',
                'verbose_name_plural': 'Procesos de Offboarding',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PasoOffboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('OMITIDO', 'Omitido')], default='PENDIENTE', max_length=12, verbose_name='Estado')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Completado')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_offboarding_completados', to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_offboarding_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('paso_plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias', to='onboarding.pasoplantillaoff', verbose_name='Paso Plantilla')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='onboarding.procesooffboarding', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Paso de Offboarding',
                'verbose_name_plural': 'Pasos de Offboarding',
                'ordering': ['proceso', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_inicio', models.DateField(default=datetime.date.today, verbose_name='Fecha de Inicio del Proceso')),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En Curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='EN_CURSO', max_length=12, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings_iniciados', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_onboarding', to='personal.personal', verbose_name='Trabajador')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='onboarding.plantillaonboarding', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Proceso de Onboarding',
                'verbose_name_plural': 'Procesos de Onboarding',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PasoOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('OMITIDO', 'Omitido')], default='PENDIENTE', max_length=12, verbose_name='Estado')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Completado')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_onboarding_completados', to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_onboarding_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('paso_plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias', to='onboarding.pasoplantilla', verbose_name='Paso Plantilla')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='onboarding.procesoonboarding', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Paso de Onboarding',
                'verbose_name_plural': 'Pasos de Onboarding',
                'ordering': ['proceso', 'orden'],
            },
        ),
    ]
