# Generated by Django 5.1.15 on 2026-03-04 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True, verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('ubigeo', models.CharField(blank=True, help_text='Código UBIGEO 6 dígitos', max_length=6)),
                ('distrito', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email_rrhh', models.EmailField(blank=True, max_length=254, verbose_name='Email RRHH')),
                ('web', models.URLField(blank=True)),
                ('regimen_laboral', models.CharField(choices=[('GENERAL', 'Régimen General'), ('MYPE', 'Régimen MYPE Tributario'), ('ESPECIAL', 'Régimen Especial Renta'), ('NRUS', 'Nuevo RUS')], default='GENERAL', max_length=12)),
                ('sector', models.CharField(choices=[('PRIVADO', 'Privado'), ('PUBLICO', 'Público'), ('MIXTO', 'Economía mixta'), ('SIN_FINES', 'Sin fines de lucro')], default='PRIVADO', max_length=10)),
                ('actividad_economica', models.CharField(blank=True, help_text='CIIU', max_length=200)),
                ('codigo_empleador', models.CharField(blank=True, help_text='Código empleador SUNAT (si aplica)', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('es_principal', models.BooleanField(default=False, help_text='Empresa principal/default del sistema')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['ruc'], name='empresa_ruc_idx'), models.Index(fields=['activa', 'es_principal'], name='empresa_activa_idx')],
            },
        ),
    ]
