# Generated by Django 5.1.15 on 2026-03-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_from',
            field=models.EmailField(blank=True, default='', help_text='Dirección "De:" (ej: rrhh@empresa.com)', max_length=254, verbose_name='Email remitente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_host',
            field=models.CharField(blank=True, default='', help_text='Servidor SMTP (ej: smtp.gmail.com, smtp.office365.com)', max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_host_password',
            field=models.CharField(blank=True, default='', help_text='Contraseña o App Password', max_length=200, verbose_name='Contraseña SMTP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_host_user',
            field=models.CharField(blank=True, default='', help_text='Email o usuario para autenticación', max_length=200, verbose_name='Usuario SMTP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_port',
            field=models.PositiveSmallIntegerField(default=587, help_text='Puerto SMTP (587=TLS, 465=SSL)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_proveedor',
            field=models.CharField(choices=[('GMAIL', 'Gmail (SMTP)'), ('OFFICE365', 'Microsoft 365 / Outlook'), ('CUSTOM', 'SMTP personalizado'), ('NONE', 'Sin correo configurado')], default='NONE', max_length=10, verbose_name='Proveedor de correo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_reply_to',
            field=models.EmailField(blank=True, default='', help_text='Dirección de respuesta (opcional)', max_length=254, verbose_name='Reply-To'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
