# Generated by Django 5.1.15 on 2026-03-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_billing_plan_suscripcion_pago'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='empresa',
            name='empresa_subdominio_idx',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cargo_representante',
            field=models.CharField(blank=True, help_text='Ej: Gerente General, Director Ejecutivo', max_length=100, verbose_name='Cargo del representante'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='firma_representante',
            field=models.ImageField(blank=True, help_text='Imagen de la firma escaneada del representante', upload_to='empresas/firmas/', verbose_name='Firma del representante legal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logotipo de la empresa para documentos PDF, contratos y reportes', upload_to='empresas/logos/', verbose_name='Logotipo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='membrete_header',
            field=models.ImageField(blank=True, help_text='Imagen de cabecera para documentos oficiales', upload_to='empresas/membretes/', verbose_name='Membrete (cabecera)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Representante legal'),
        ),
    ]
