# Generated by Django 5.1.15 on 2026-03-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_remove_empresa_empresa_subdominio_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dia_fin_corte',
            field=models.PositiveSmallIntegerField(default=21, help_text='Día del mes actual donde termina el corte de planilla', verbose_name='Día fin corte'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dia_inicio_corte',
            field=models.PositiveSmallIntegerField(default=22, help_text='Día del mes anterior donde inicia el corte de planilla', verbose_name='Día inicio corte'),
        ),
    ]
