# Generated by Django 5.1.15 on 2026-03-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_empresa_dia_fin_corte_empresa_dia_inicio_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nro_doc_representante',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nro. documento representante'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_doc_representante',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('CE', 'Carné de Extranjería'), ('Pasaporte', 'Pasaporte')], default='DNI', max_length=20, verbose_name='Tipo doc. representante'),
        ),
    ]
