# Generated by Django 5.1.15 on 2026-03-02 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0012_add_categoria_pension_cuspp_asigfamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('CLIMA', 'Clima Laboral'), ('PULSO', 'Pulso Rápido'), ('SATISFACCION', 'Satisfacción'), ('ENPS', 'eNPS'), ('SALIDA', 'Encuesta de Salida'), ('ONBOARDING', 'Encuesta Onboarding'), ('CUSTOM', 'Personalizada')], default='CLIMA', max_length=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROGRAMADA', 'Programada'), ('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada'), ('ARCHIVADA', 'Archivada')], default='BORRADOR', max_length=12)),
                ('anonima', models.BooleanField(default=True, help_text='Si es anónima, no se vincula respuesta con trabajador', verbose_name='Anónima')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('aplica_grupos', models.CharField(blank=True, choices=[('', 'Todos'), ('STAFF', 'Solo STAFF'), ('RCO', 'Solo RCO')], max_length=20, verbose_name='Grupo')),
                ('max_respuestas', models.PositiveIntegerField(default=0, help_text='0 = sin límite')),
                ('recordatorio_dias', models.PositiveSmallIntegerField(default=3, help_text='0 = sin recordatorios', verbose_name='Recordatorio cada (días)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aplica_areas', models.ManyToManyField(blank=True, help_text='Vacío = aplica a todas', related_name='encuestas', to='personal.area', verbose_name='Áreas participantes')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Pregunta')),
                ('tipo', models.CharField(choices=[('ESCALA_5', 'Escala 1-5'), ('ESCALA_10', 'Escala 0-10 (NPS)'), ('OPCION', 'Opción Múltiple'), ('SI_NO', 'Sí / No'), ('TEXTO', 'Texto Libre'), ('MATRIZ', 'Matriz')], default='ESCALA_5', max_length=10)),
                ('obligatoria', models.BooleanField(default=True)),
                ('opciones', models.JSONField(blank=True, default=list, help_text='Lista de opciones para preguntas de opción múltiple. Ej: ["Muy bueno","Bueno","Regular","Malo"]', verbose_name='Opciones')),
                ('categoria', models.CharField(blank=True, help_text='Ej: Liderazgo, Comunicación, Ambiente, Compensación', max_length=50, verbose_name='Categoría/Dimensión')),
                ('orden', models.PositiveSmallIntegerField(default=10)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='encuestas.encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_anonima', models.CharField(blank=True, max_length=100)),
                ('grupo_anonimo', models.CharField(blank=True, max_length=10)),
                ('respuestas', models.JSONField(default=dict, help_text='Dict { pregunta_id: valor }', verbose_name='Respuestas')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios Adicionales')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.encuesta')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_encuestas', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Respuesta a Encuesta',
                'verbose_name_plural': 'Respuestas a Encuestas',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_participantes', models.PositiveIntegerField(default=0)),
                ('tasa_participacion', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('enps_score', models.IntegerField(blank=True, help_text='Employee Net Promoter Score (-100 a +100)', null=True, verbose_name='eNPS Score')),
                ('enps_promotores', models.PositiveIntegerField(default=0)),
                ('enps_pasivos', models.PositiveIntegerField(default=0)),
                ('enps_detractores', models.PositiveIntegerField(default=0)),
                ('puntajes_dimension', models.JSONField(blank=True, default=dict, verbose_name='Puntajes por Dimensión')),
                ('puntaje_general', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('encuesta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='encuestas.encuesta')),
            ],
            options={
                'verbose_name': 'Resultado de Encuesta',
                'verbose_name_plural': 'Resultados de Encuestas',
            },
        ),
    ]
